// NEDI - MoYS RF-NDP Indicator Data Structure
export type IndicatorData = {
  id: string
  organization: string
  indicator: string
  year: number
  region: string
  male: number
  female: number
  total: number
  referenceSource: string
  category: "finance" | "training" | "sport_financing"
}

export type OrganizationSummary = {
  id: string
  name: string
  fullName: string
  description: string
  icon: string
  color: string
  totalBeneficiaries: number
  activePrograms: number
}

// NEDI Financial Access Data
export const nediFinanceData: IndicatorData[] = [
  // 2022 Data
  {
    id: "nf1",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "GBA",
    male: 117,
    female: 5,
    total: 122,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf2",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "WCR",
    male: 89,
    female: 10,
    total: 99,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf3",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "NBR",
    male: 49,
    female: 2,
    total: 51,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf4",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "LRR",
    male: 52,
    female: 2,
    total: 54,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf5",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "CRR",
    male: 54,
    female: 1,
    total: 55,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf6",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "URR",
    male: 54,
    female: 3,
    total: 57,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },

  // 2023 Data
  {
    id: "nf7",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "GBA",
    male: 159,
    female: 7,
    total: 166,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf8",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "WCR",
    male: 201,
    female: 9,
    total: 210,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf9",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "NBR",
    male: 121,
    female: 4,
    total: 125,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf10",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "LRR",
    male: 101,
    female: 4,
    total: 105,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf11",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "CRR",
    male: 96,
    female: 7,
    total: 103,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf12",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "URR",
    male: 166,
    female: 8,
    total: 174,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },

  // 2024 Data
  {
    id: "nf13",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2024,
    region: "GBA",
    male: 6,
    female: 2,
    total: 8,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf14",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2024,
    region: "WCR",
    male: 4,
    female: 2,
    total: 6,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf15",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2024,
    region: "NBR",
    male: 3,
    female: 1,
    total: 4,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf16",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2024,
    region: "LRR",
    male: 2,
    female: 2,
    total: 4,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf17",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2024,
    region: "CRR",
    male: 2,
    female: 1,
    total: 3,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
  {
    id: "nf18",
    organization: "NEDI",
    indicator: "Youth-owned business with access to finance",
    year: 2024,
    region: "URR",
    male: 2,
    female: 2,
    total: 4,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "finance",
  },
]

// NEDI Training Data
export const nediTrainingData: IndicatorData[] = [
  // 2022 Data
  {
    id: "nt1",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "GBA",
    male: 71,
    female: 54,
    total: 125,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt2",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "WCR",
    male: 53,
    female: 62,
    total: 115,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt3",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "NBR",
    male: 55,
    female: 40,
    total: 95,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt4",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "LRR",
    male: 60,
    female: 42,
    total: 102,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt5",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "CRR",
    male: 38,
    female: 22,
    total: 60,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt6",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "URR",
    male: 140,
    female: 30,
    total: 170,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },

  // 2023 Data
  {
    id: "nt7",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "GBA",
    male: 105,
    female: 70,
    total: 175,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt8",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "WCR",
    male: 172,
    female: 50,
    total: 222,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt9",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "NBR",
    male: 95,
    female: 30,
    total: 125,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt10",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "LRR",
    male: 75,
    female: 40,
    total: 115,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt11",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "CRR",
    male: 72,
    female: 40,
    total: 112,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt12",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "URR",
    male: 135,
    female: 50,
    total: 185,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },

  // 2024 Data
  {
    id: "nt13",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "GBA",
    male: 506,
    female: 98,
    total: 604,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt14",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "WCR",
    male: 492,
    female: 81,
    total: 573,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt15",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "NBR",
    male: 130,
    female: 67,
    total: 197,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt16",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "LRR",
    male: 256,
    female: 98,
    total: 354,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt17",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "CRR",
    male: 154,
    female: 86,
    total: 240,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
  {
    id: "nt18",
    organization: "NEDI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "URR",
    male: 241,
    female: 87,
    total: 328,
    referenceSource: "NEDI Annual Report & Migrant Returnee Training",
    category: "training",
  },
]

// PIA Training Data
export const piaTrainingData: IndicatorData[] = [
  // 2022 Data
  {
    id: "pt1",
    organization: "PIA",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "KM",
    male: 44,
    female: 78,
    total: 122,
    referenceSource: "Students who graduated from our Skills Training Centre in Bakau",
    category: "training",
  },

  // 2023 Data
  {
    id: "pt2",
    organization: "PIA",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "KM",
    male: 49,
    female: 60,
    total: 109,
    referenceSource: "Students who graduated from our Skills Training Centre in Bakau",
    category: "training",
  },

  // 2024 Data
  {
    id: "pt3",
    organization: "PIA",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "KM",
    male: 53,
    female: 77,
    total: 130,
    referenceSource: "Students who graduated from our Skills Training Centre in Bakau",
    category: "training",
  },
]

// GSI Data
export const gsiFinanceData: IndicatorData[] = [
  // 2022 Data
  {
    id: "gf1",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "KM",
    male: 0,
    female: 1,
    total: 1,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },
  {
    id: "gf2",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "WCR",
    male: 0,
    female: 1,
    total: 1,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },
  {
    id: "gf3",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "LRR",
    male: 0,
    female: 1,
    total: 1,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },
  {
    id: "gf4",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2022,
    region: "CRR",
    male: 0,
    female: 1,
    total: 1,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },

  // 2023 Data
  {
    id: "gf5",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "WCR",
    male: 5,
    female: 2,
    total: 7,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },
  {
    id: "gf6",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "NBR",
    male: 10,
    female: 16,
    total: 26,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },
  {
    id: "gf7",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "LRR",
    male: 10,
    female: 5,
    total: 15,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },
  {
    id: "gf8",
    organization: "GSI",
    indicator: "Youth-owned business with access to finance",
    year: 2023,
    region: "CRR",
    male: 0,
    female: 2,
    total: 2,
    referenceSource: "Youths that get access to finance with GSI",
    category: "finance",
  },
]

export const gsiTrainingData: IndicatorData[] = [
  // 2022 Data
  {
    id: "gt1",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "KM",
    male: 1,
    female: 4,
    total: 5,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt2",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "WCR",
    male: 6,
    female: 3,
    total: 9,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt3",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "NBR",
    male: 3,
    female: 6,
    total: 9,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt4",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "LRR",
    male: 2,
    female: 1,
    total: 3,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt5",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "CRR",
    male: 4,
    female: 4,
    total: 8,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt6",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2022,
    region: "URR",
    male: 0,
    female: 1,
    total: 1,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },

  // 2023 Data
  {
    id: "gt7",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "KM",
    male: 1,
    female: 0,
    total: 1,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt8",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "WCR",
    male: 14,
    female: 14,
    total: 28,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt9",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "NBR",
    male: 23,
    female: 32,
    total: 55,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt10",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "LRR",
    male: 18,
    female: 16,
    total: 34,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt11",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "CRR",
    male: 3,
    female: 5,
    total: 8,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt12",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2023,
    region: "URR",
    male: 4,
    female: 4,
    total: 8,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },

  // 2024 Data
  {
    id: "gt13",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "KM",
    male: 3,
    female: 3,
    total: 6,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt14",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "WCR",
    male: 12,
    female: 8,
    total: 20,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt15",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "NBR",
    male: 9,
    female: 23,
    total: 32,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt16",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "LRR",
    male: 7,
    female: 11,
    total: 18,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt17",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "CRR",
    male: 3,
    female: 6,
    total: 9,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
  {
    id: "gt18",
    organization: "GSI",
    indicator: "Youth graduating from entrepreneurship/skills/apprenticeship trainings",
    year: 2024,
    region: "URR",
    male: 0,
    female: 2,
    total: 2,
    referenceSource: "Students who graduated from our Skills Training Centre in Chamen Village",
    category: "training",
  },
]

// NYSS Training Data
export const nyssTrainingData: IndicatorData[] = [
  // 2022 Data
  {
    id: "nyt1",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2022,
    region: "BJL",
    male: 12,
    female: 28,
    total: 40,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt2",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2022,
    region: "KM",
    male: 32,
    female: 18,
    total: 50,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt3",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2022,
    region: "WCR",
    male: 25,
    female: 36,
    total: 61,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt4",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2022,
    region: "NBR",
    male: 20,
    female: 10,
    total: 30,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt5",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2022,
    region: "LRR",
    male: 30,
    female: 5,
    total: 35,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt6",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2022,
    region: "CRR",
    male: 15,
    female: 20,
    total: 35,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt7",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2022,
    region: "URR",
    male: 20,
    female: 15,
    total: 35,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },

  // 2023 Data
  {
    id: "nyt8",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2023,
    region: "BJL",
    male: 9,
    female: 10,
    total: 19,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt9",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2023,
    region: "KM",
    male: 12,
    female: 20,
    total: 32,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt10",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2023,
    region: "WCR",
    male: 6,
    female: 15,
    total: 21,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt11",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2023,
    region: "NBR",
    male: 3,
    female: 4,
    total: 7,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt12",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2023,
    region: "LRR",
    male: 5,
    female: 8,
    total: 13,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt13",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2023,
    region: "CRR",
    male: 2,
    female: 5,
    total: 7,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
  {
    id: "nyt14",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2023,
    region: "URR",
    male: 3,
    female: 4,
    total: 7,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },

  // 2024 Data
  {
    id: "nyt15",
    organization: "NYSS",
    indicator: "Youth training in entrepreneurship, enterprise development, coaching, business plan development",
    year: 2024,
    region: "National",
    male: 53,
    female: 47,
    total: 100,
    referenceSource: "Annual report/quarterly Reports",
    category: "training",
  },
]

// NSC Sport Financing Data
export const nscSportFinancingData: IndicatorData[] = [
  {
    id: "nsf1",
    organization: "NSC",
    indicator: "Youth-owned sports businesses with access to finance",
    year: 2022,
    region: "GBA",
    male: 15,
    female: 8,
    total: 23,
    referenceSource: "NSC Annual Report 2022 - Sport Business Development",
    category: "sport_financing",
  },
  {
    id: "nsf2",
    organization: "NSC",
    indicator: "Youth-owned sports businesses with access to finance",
    year: 2022,
    region: "WCR",
    male: 12,
    female: 6,
    total: 18,
    referenceSource: "NSC Annual Report 2022 - Sport Business Development",
    category: "sport_financing",
  },
  {
    id: "nsf3",
    organization: "NSC",
    indicator: "Youth-owned sports businesses with access to finance",
    year: 2023,
    region: "GBA",
    male: 22,
    female: 12,
    total: 34,
    referenceSource: "NSC Annual Report 2023 - Sport Business Development",
    category: "sport_financing",
  },
  {
    id: "nsf4",
    organization: "NSC",
    indicator: "Youth-owned sports businesses with access to finance",
    year: 2023,
    region: "WCR",
    male: 18,
    female: 9,
    total: 27,
    referenceSource: "NSC Annual Report 2023 - Sport Business Development",
    category: "sport_financing",
  },
  {
    id: "nsf5",
    organization: "NSC",
    indicator: "Youth-owned sports businesses with access to finance",
    year: 2024,
    region: "GBA",
    male: 28,
    female: 15,
    total: 43,
    referenceSource: "NSC Annual Report 2024 - Sport Business Development",
    category: "sport_financing",
  },
]

// Organization Summary Data
export const organizationSummaries: OrganizationSummary[] = [
  {
    id: "nedi",
    name: "NEDI",
    fullName: "National Enterprise Development Initiative",
    description: "Leading enterprise development and migrant returnee support programs",
    icon: "Building2",
    color: "blue",
    totalBeneficiaries: 4625,
    activePrograms: 12,
  },
  {
    id: "pia",
    name: "PIA",
    fullName: "President International Award",
    description: "Skills training and youth development programs",
    icon: "Award",
    color: "purple",
    totalBeneficiaries: 361,
    activePrograms: 3,
  },
  {
    id: "gsi",
    name: "GSI",
    fullName: "Gambia Songhai Initiative",
    description: "Agricultural and entrepreneurship training programs",
    icon: "Sprout",
    color: "green",
    totalBeneficiaries: 349,
    activePrograms: 8,
  },
  {
    id: "nyss",
    name: "NYSS",
    fullName: "National Youth Service Scheme",
    description: "Youth service and entrepreneurship development",
    icon: "Users",
    color: "orange",
    totalBeneficiaries: 482,
    activePrograms: 5,
  },
  {
    id: "nsc",
    name: "NSC",
    fullName: "National Sports Council",
    description: "Sports development and athlete financing programs",
    icon: "Trophy",
    color: "red",
    totalBeneficiaries: 145,
    activePrograms: 4,
  },
  {
    id: "nyc",
    name: "NYC",
    fullName: "National Youth Council",
    description: "Youth leadership and community development programs (Est. 2000)",
    icon: "Target",
    color: "indigo",
    totalBeneficiaries: 3850,
    activePrograms: 25,
  },
]

// Combined data arrays
export const allIndicatorData = [
  ...nediFinanceData,
  ...nediTrainingData,
  ...piaTrainingData,
  ...gsiFinanceData,
  ...gsiTrainingData,
  ...nyssTrainingData,
  ...nscSportFinancingData,
]

// Export alias for backward compatibility
export const indicatorData = allIndicatorData
