// NYC (National Youth Council) Activities Data Structure
export interface NYCActivity {
  id: string
  activityName: string
  category: string
  region: string
  year: number
  beneficiaries: number
  male: number
  female: number
  fundingPartner: string
  description: string
  status: "Completed" | "Ongoing" | "Planned"
}

export interface YouthOrganization {
  id: string
  name: string
  fullName: string
  description: string
  region: string
  established: number
  members: number
  activities: string[]
  contact: {
    email: string
    phone: string
    address: string
  }
}

// NYC Activities Data (2022-2024)
export const allNYCActivities: NYCActivity[] = [
  {
    id: "nyc1",
    activityName: "Youth Leadership Training Program",
    category: "Leadership Development",
    region: "GBA",
    year: 2022,
    beneficiaries: 150,
    male: 75,
    female: 75,
    fundingPartner: "UNDP",
    description: "Comprehensive leadership training for young people in Greater Banjul Area",
    status: "Completed",
  },
  {
    id: "nyc2",
    activityName: "Digital Skills Bootcamp",
    category: "Skills Development",
    region: "KM",
    year: 2022,
    beneficiaries: 200,
    male: 120,
    female: 80,
    fundingPartner: "EU",
    description: "Intensive digital literacy and coding training program",
    status: "Completed",
  },
  {
    id: "nyc3",
    activityName: "Youth Entrepreneurship Summit",
    category: "Entrepreneurship",
    region: "WCR",
    year: 2022,
    beneficiaries: 300,
    male: 180,
    female: 120,
    fundingPartner: "World Bank",
    description: "Annual summit bringing together young entrepreneurs and mentors",
    status: "Completed",
  },
  {
    id: "nyc4",
    activityName: "Climate Action Youth Forum",
    category: "Environmental",
    region: "NBR",
    year: 2022,
    beneficiaries: 180,
    male: 90,
    female: 90,
    fundingPartner: "GEF",
    description: "Youth-led climate change awareness and action planning",
    status: "Completed",
  },
  {
    id: "nyc5",
    activityName: "Sports for Development Program",
    category: "Sports & Recreation",
    region: "LRR",
    year: 2022,
    beneficiaries: 250,
    male: 140,
    female: 110,
    fundingPartner: "FIFA Foundation",
    description: "Using sports as a tool for youth development and social cohesion",
    status: "Completed",
  },
  {
    id: "nyc6",
    activityName: "Youth Health Advocacy Campaign",
    category: "Health & Wellness",
    region: "CRR",
    year: 2022,
    beneficiaries: 400,
    male: 200,
    female: 200,
    fundingPartner: "WHO",
    description: "Peer-to-peer health education and advocacy program",
    status: "Completed",
  },
  {
    id: "nyc7",
    activityName: "Cultural Heritage Preservation Project",
    category: "Arts & Culture",
    region: "URR",
    year: 2022,
    beneficiaries: 120,
    male: 60,
    female: 60,
    fundingPartner: "UNESCO",
    description: "Youth-led initiative to document and preserve local cultural practices",
    status: "Completed",
  },
  {
    id: "nyc8",
    activityName: "Advanced Leadership Academy",
    category: "Leadership Development",
    region: "GBA",
    year: 2023,
    beneficiaries: 180,
    male: 90,
    female: 90,
    fundingPartner: "UNDP",
    description: "Advanced leadership training for youth council members",
    status: "Completed",
  },
  {
    id: "nyc9",
    activityName: "Tech Innovation Hub",
    category: "Skills Development",
    region: "KM",
    year: 2023,
    beneficiaries: 250,
    male: 150,
    female: 100,
    fundingPartner: "EU",
    description: "Technology incubator and innovation space for young entrepreneurs",
    status: "Completed",
  },
  {
    id: "nyc10",
    activityName: "Green Business Incubator",
    category: "Entrepreneurship",
    region: "WCR",
    year: 2023,
    beneficiaries: 160,
    male: 80,
    female: 80,
    fundingPartner: "World Bank",
    description: "Supporting eco-friendly business ventures by young entrepreneurs",
    status: "Completed",
  },
  {
    id: "nyc11",
    activityName: "Youth Climate Summit",
    category: "Environmental",
    region: "NBR",
    year: 2023,
    beneficiaries: 220,
    male: 110,
    female: 110,
    fundingPartner: "GEF",
    description: "National youth climate summit with international participation",
    status: "Completed",
  },
  {
    id: "nyc12",
    activityName: "Community Sports League",
    category: "Sports & Recreation",
    region: "LRR",
    year: 2023,
    beneficiaries: 300,
    male: 180,
    female: 120,
    fundingPartner: "FIFA Foundation",
    description: "Establishing community-based sports leagues for youth engagement",
    status: "Completed",
  },
  {
    id: "nyc13",
    activityName: "Mental Health First Aid Training",
    category: "Health & Wellness",
    region: "CRR",
    year: 2023,
    beneficiaries: 150,
    male: 70,
    female: 80,
    fundingPartner: "WHO",
    description: "Training youth as mental health first aid providers",
    status: "Completed",
  },
  {
    id: "nyc14",
    activityName: "Youth Arts Festival",
    category: "Arts & Culture",
    region: "URR",
    year: 2023,
    beneficiaries: 280,
    male: 140,
    female: 140,
    fundingPartner: "UNESCO",
    description: "Annual festival showcasing youth talent in arts and culture",
    status: "Completed",
  },
  {
    id: "nyc15",
    activityName: "Civic Education Program",
    category: "Leadership Development",
    region: "GBA",
    year: 2023,
    beneficiaries: 200,
    male: 100,
    female: 100,
    fundingPartner: "UNDP",
    description: "Educating youth on civic responsibilities and democratic participation",
    status: "Completed",
  },
  {
    id: "nyc16",
    activityName: "AI and Machine Learning Workshop",
    category: "Skills Development",
    region: "KM",
    year: 2024,
    beneficiaries: 100,
    male: 60,
    female: 40,
    fundingPartner: "EU",
    description: "Introduction to artificial intelligence and machine learning for youth",
    status: "Ongoing",
  },
  {
    id: "nyc17",
    activityName: "Social Enterprise Accelerator",
    category: "Entrepreneurship",
    region: "WCR",
    year: 2024,
    beneficiaries: 80,
    male: 40,
    female: 40,
    fundingPartner: "World Bank",
    description: "Accelerator program for youth-led social enterprises",
    status: "Ongoing",
  },
  {
    id: "nyc18",
    activityName: "Renewable Energy Youth Initiative",
    category: "Environmental",
    region: "NBR",
    year: 2024,
    beneficiaries: 120,
    male: 70,
    female: 50,
    fundingPartner: "GEF",
    description: "Training youth in renewable energy technologies and installation",
    status: "Ongoing",
  },
  {
    id: "nyc19",
    activityName: "Paralympic Sports Development",
    category: "Sports & Recreation",
    region: "LRR",
    year: 2024,
    beneficiaries: 60,
    male: 35,
    female: 25,
    fundingPartner: "FIFA Foundation",
    description: "Developing Paralympic sports opportunities for youth with disabilities",
    status: "Ongoing",
  },
  {
    id: "nyc20",
    activityName: "Youth Nutrition Champions",
    category: "Health & Wellness",
    region: "CRR",
    year: 2024,
    beneficiaries: 180,
    male: 80,
    female: 100,
    fundingPartner: "WHO",
    description: "Training youth as nutrition advocates in their communities",
    status: "Ongoing",
  },
  {
    id: "nyc21",
    activityName: "Digital Storytelling Workshop",
    category: "Arts & Culture",
    region: "URR",
    year: 2024,
    beneficiaries: 90,
    male: 45,
    female: 45,
    fundingPartner: "UNESCO",
    description: "Teaching youth to create and share digital stories about their communities",
    status: "Ongoing",
  },
  {
    id: "nyc22",
    activityName: "Youth Parliament Simulation",
    category: "Leadership Development",
    region: "GBA",
    year: 2024,
    beneficiaries: 150,
    male: 75,
    female: 75,
    fundingPartner: "UNDP",
    description: "Simulated parliamentary sessions to teach democratic processes",
    status: "Planned",
  },
  {
    id: "nyc23",
    activityName: "Blockchain and Cryptocurrency Education",
    category: "Skills Development",
    region: "KM",
    year: 2024,
    beneficiaries: 80,
    male: 50,
    female: 30,
    fundingPartner: "EU",
    description: "Educational program on blockchain technology and digital currencies",
    status: "Planned",
  },
  {
    id: "nyc24",
    activityName: "Agri-Tech Innovation Lab",
    category: "Entrepreneurship",
    region: "WCR",
    year: 2024,
    beneficiaries: 100,
    male: 60,
    female: 40,
    fundingPartner: "World Bank",
    description: "Innovation lab focusing on agricultural technology solutions",
    status: "Planned",
  },
  {
    id: "nyc25",
    activityName: "Ocean Conservation Youth Network",
    category: "Environmental",
    region: "NBR",
    year: 2024,
    beneficiaries: 140,
    male: 70,
    female: 70,
    fundingPartner: "GEF",
    description: "Youth network for ocean and marine conservation activities",
    status: "Planned",
  },
]

// Youth Organizations Data
export const youthOrganizations: YouthOrganization[] = [
  {
    id: "org1",
    name: "NYC",
    fullName: "National Youth Council",
    description: "Umbrella organization for youth development in The Gambia, established in 2000",
    region: "National",
    established: 2000,
    members: 15000,
    activities: ["Leadership Development", "Skills Training", "Advocacy"],
    contact: {
      email: "info@nyc.gov.gm",
      phone: "+220 123 4567",
      address: "Banjul, The Gambia",
    },
  },
  {
    id: "org2",
    name: "YAAG",
    fullName: "Young Achievers Association of Gambia",
    description: "Empowering young people through education and entrepreneurship",
    region: "GBA",
    established: 2015,
    members: 2500,
    activities: ["Entrepreneurship", "Education", "Mentorship"],
    contact: {
      email: "contact@yaag.gm",
      phone: "+220 234 5678",
      address: "Kanifing, The Gambia",
    },
  },
  {
    id: "org3",
    name: "GYDA",
    fullName: "Gambia Youth Development Association",
    description: "Promoting youth participation in development activities",
    region: "WCR",
    established: 2012,
    members: 1800,
    activities: ["Community Development", "Skills Training", "Sports"],
    contact: {
      email: "info@gyda.gm",
      phone: "+220 345 6789",
      address: "Brikama, The Gambia",
    },
  },
  {
    id: "org4",
    name: "NBYF",
    fullName: "North Bank Youth Forum",
    description: "Advocating for youth rights and opportunities in North Bank Region",
    region: "NBR",
    established: 2018,
    members: 1200,
    activities: ["Advocacy", "Environmental Protection", "Health"],
    contact: {
      email: "nbyf@gmail.com",
      phone: "+220 456 7890",
      address: "Kerewan, The Gambia",
    },
  },
  {
    id: "org5",
    name: "LRRYC",
    fullName: "Lower River Region Youth Council",
    description: "Coordinating youth activities in Lower River Region",
    region: "LRR",
    established: 2016,
    members: 900,
    activities: ["Agriculture", "Sports", "Cultural Activities"],
    contact: {
      email: "lrryc@yahoo.com",
      phone: "+220 567 8901",
      address: "Mansakonko, The Gambia",
    },
  },
]

// Summary for registered organizations
export const registeredOrgsSummary = {
  totalRegistered: 301,
  byRegion: {
    National: 42,
    BJL: 11,
    KMC: 17,
    WCR: 45,
    LRR: 20,
    NBR: 76,
    CRR: 39,
    URR: 51,
  },
}
