// NYSS (National Youth Service Scheme) Database 2022-2025
export interface NYSSGraduate {
  id: string
  name: string
  age: number
  gender: "Male" | "Female"
  region: string
  trainingProgram: string
  trainingInstitution: string
  trainingDuration: string
  graduationYear: number
  employmentStatus: "Employed" | "Self-Employed" | "Seeking Employment" | "Further Education"
  sector: string
  skills: string[]
  certifications: string[]
  dateRegistered: string
  contact?: string
}

export interface NYSSProgram {
  id: string
  programName: string
  institution: string
  region: string
  year: number
  totalGraduates: number
  maleGraduates: number
  femaleGraduates: number
  employmentRate: number
  sector: string
  duration: string
  fundingPartner: string
}

// NYSS Programs Data (2022-2025)
export const nyssPrograms: NYSSProgram[] = [
  // 2022 Programs
  {
    id: "nyss_prog_1",
    programName: "Entrepreneurship & Business Management",
    institution: "GTTI",
    region: "KM",
    year: 2022,
    totalGraduates: 125,
    maleGraduates: 71,
    femaleGraduates: 54,
    employmentRate: 68,
    sector: "Business & Entrepreneurship",
    duration: "6 months",
    fundingPartner: "World Bank",
  },
  {
    id: "nyss_prog_2",
    programName: "Digital Skills & ICT",
    institution: "UTG",
    region: "GBA",
    year: 2022,
    totalGraduates: 150,
    maleGraduates: 85,
    femaleGraduates: 65,
    employmentRate: 72,
    sector: "Information Technology",
    duration: "4 months",
    fundingPartner: "EU",
  },
  {
    id: "nyss_prog_3",
    programName: "Agricultural Skills Training",
    institution: "MDI",
    region: "CRR",
    year: 2022,
    totalGraduates: 98,
    maleGraduates: 60,
    femaleGraduates: 38,
    employmentRate: 65,
    sector: "Agriculture",
    duration: "8 months",
    fundingPartner: "FAO",
  },
  {
    id: "nyss_prog_4",
    programName: "Hospitality & Tourism",
    institution: "GTTI",
    region: "WCR",
    year: 2022,
    totalGraduates: 87,
    maleGraduates: 42,
    femaleGraduates: 45,
    employmentRate: 58,
    sector: "Tourism & Hospitality",
    duration: "6 months",
    fundingPartner: "UNDP",
  },

  // 2023 Programs
  {
    id: "nyss_prog_5",
    programName: "Advanced Entrepreneurship",
    institution: "GTTI",
    region: "KM",
    year: 2023,
    totalGraduates: 140,
    maleGraduates: 82,
    femaleGraduates: 58,
    employmentRate: 75,
    sector: "Business & Entrepreneurship",
    duration: "6 months",
    fundingPartner: "World Bank",
  },
  {
    id: "nyss_prog_6",
    programName: "Software Development",
    institution: "UTG",
    region: "GBA",
    year: 2023,
    totalGraduates: 110,
    maleGraduates: 75,
    femaleGraduates: 35,
    employmentRate: 80,
    sector: "Information Technology",
    duration: "8 months",
    fundingPartner: "EU",
  },
  {
    id: "nyss_prog_7",
    programName: "Modern Farming Techniques",
    institution: "MDI",
    region: "NBR",
    year: 2023,
    totalGraduates: 105,
    maleGraduates: 68,
    femaleGraduates: 37,
    employmentRate: 70,
    sector: "Agriculture",
    duration: "6 months",
    fundingPartner: "FAO",
  },
  {
    id: "nyss_prog_8",
    programName: "Healthcare Services",
    institution: "SMC",
    region: "LRR",
    year: 2023,
    totalGraduates: 92,
    maleGraduates: 35,
    femaleGraduates: 57,
    employmentRate: 85,
    sector: "Healthcare",
    duration: "12 months",
    fundingPartner: "WHO",
  },

  // 2024 Programs
  {
    id: "nyss_prog_9",
    programName: "Green Energy & Sustainability",
    institution: "GTTI",
    region: "WCR",
    year: 2024,
    totalGraduates: 78,
    maleGraduates: 52,
    femaleGraduates: 26,
    employmentRate: 62,
    sector: "Renewable Energy",
    duration: "6 months",
    fundingPartner: "GEF",
  },
  {
    id: "nyss_prog_10",
    programName: "Automotive Mechanics",
    institution: "GTTI",
    region: "KM",
    year: 2024,
    totalGraduates: 95,
    maleGraduates: 88,
    femaleGraduates: 7,
    employmentRate: 68,
    sector: "Technical Skills",
    duration: "9 months",
    fundingPartner: "UNDP",
  },
  {
    id: "nyss_prog_11",
    programName: "Fashion & Textile Design",
    institution: "NEDI",
    region: "GBA",
    year: 2024,
    totalGraduates: 120,
    maleGraduates: 25,
    femaleGraduates: 95,
    employmentRate: 58,
    sector: "Creative Industries",
    duration: "6 months",
    fundingPartner: "EU",
  },
  {
    id: "nyss_prog_12",
    programName: "Construction & Carpentry",
    institution: "GTTI",
    region: "URR",
    year: 2024,
    totalGraduates: 85,
    maleGraduates: 79,
    femaleGraduates: 6,
    employmentRate: 72,
    sector: "Construction",
    duration: "8 months",
    fundingPartner: "World Bank",
  },

  // 2025 Planned Programs
  {
    id: "nyss_prog_13",
    programName: "AI & Data Science",
    institution: "UTG",
    region: "GBA",
    year: 2025,
    totalGraduates: 0,
    maleGraduates: 0,
    femaleGraduates: 0,
    employmentRate: 0,
    sector: "Information Technology",
    duration: "10 months",
    fundingPartner: "EU",
  },
  {
    id: "nyss_prog_14",
    programName: "Agribusiness Management",
    institution: "MDI",
    region: "CRR",
    year: 2025,
    totalGraduates: 0,
    maleGraduates: 0,
    femaleGraduates: 0,
    employmentRate: 0,
    sector: "Agriculture",
    duration: "6 months",
    fundingPartner: "FAO",
  },
]

// Sample NYSS Graduate Data
export const nyssGraduates: NYSSGraduate[] = [
  {
    id: "NYSS_G001",
    name: "Muhammed Jallow",
    age: 24,
    gender: "Male",
    region: "KM",
    trainingProgram: "Entrepreneurship & Business Management",
    trainingInstitution: "GTTI",
    trainingDuration: "6 months",
    graduationYear: 2022,
    employmentStatus: "Self-Employed",
    sector: "Retail Business",
    skills: ["Business Planning", "Financial Management", "Marketing"],
    certifications: ["Business Management Certificate", "Entrepreneurship Diploma"],
    dateRegistered: "2022-01-15",
    contact: "muhammed.jallow@email.com",
  },
  {
    id: "NYSS_G002",
    name: "Aminata Sowe",
    age: 22,
    gender: "Female",
    region: "GBA",
    trainingProgram: "Digital Skills & ICT",
    trainingInstitution: "UTG",
    trainingDuration: "4 months",
    graduationYear: 2022,
    employmentStatus: "Employed",
    sector: "Technology",
    skills: ["Web Development", "Digital Marketing", "Graphic Design"],
    certifications: ["ICT Certificate", "Digital Skills Diploma"],
    dateRegistered: "2022-03-20",
    contact: "aminata.sowe@email.com",
  },
  {
    id: "NYSS_G003",
    name: "Bakary Ceesay",
    age: 26,
    gender: "Male",
    region: "CRR",
    trainingProgram: "Agricultural Skills Training",
    trainingInstitution: "MDI",
    trainingDuration: "8 months",
    graduationYear: 2022,
    employmentStatus: "Self-Employed",
    sector: "Agriculture",
    skills: ["Modern Farming", "Irrigation", "Crop Management"],
    certifications: ["Agricultural Skills Certificate"],
    dateRegistered: "2022-02-10",
    contact: "bakary.ceesay@email.com",
  },
  {
    id: "NYSS_G004",
    name: "Fatou Jatta",
    age: 23,
    gender: "Female",
    region: "WCR",
    trainingProgram: "Hospitality & Tourism",
    trainingInstitution: "GTTI",
    trainingDuration: "6 months",
    graduationYear: 2022,
    employmentStatus: "Employed",
    sector: "Tourism",
    skills: ["Customer Service", "Event Management", "Food Service"],
    certifications: ["Hospitality Certificate"],
    dateRegistered: "2022-04-05",
    contact: "fatou.jatta@email.com",
  },
  {
    id: "NYSS_G005",
    name: "Lamin Drammeh",
    age: 25,
    gender: "Male",
    region: "KM",
    trainingProgram: "Advanced Entrepreneurship",
    trainingInstitution: "GTTI",
    trainingDuration: "6 months",
    graduationYear: 2023,
    employmentStatus: "Self-Employed",
    sector: "Manufacturing",
    skills: ["Business Development", "Product Design", "Supply Chain"],
    certifications: ["Advanced Entrepreneurship Diploma"],
    dateRegistered: "2023-01-12",
    contact: "lamin.drammeh@email.com",
  },
  {
    id: "NYSS_G006",
    name: "Isatou Touray",
    age: 21,
    gender: "Female",
    region: "GBA",
    trainingProgram: "Software Development",
    trainingInstitution: "UTG",
    trainingDuration: "8 months",
    graduationYear: 2023,
    employmentStatus: "Employed",
    sector: "Technology",
    skills: ["Programming", "Database Management", "Mobile Development"],
    certifications: ["Software Development Diploma", "Java Certification"],
    dateRegistered: "2023-02-18",
    contact: "isatou.touray@email.com",
  },
  {
    id: "NYSS_G007",
    name: "Modou Bah",
    age: 27,
    gender: "Male",
    region: "NBR",
    trainingProgram: "Modern Farming Techniques",
    trainingInstitution: "MDI",
    trainingDuration: "6 months",
    graduationYear: 2023,
    employmentStatus: "Self-Employed",
    sector: "Agriculture",
    skills: ["Greenhouse Farming", "Organic Farming", "Pest Management"],
    certifications: ["Modern Agriculture Certificate"],
    dateRegistered: "2023-03-22",
    contact: "modou.bah@email.com",
  },
  {
    id: "NYSS_G008",
    name: "Mariama Sanneh",
    age: 24,
    gender: "Female",
    region: "LRR",
    trainingProgram: "Healthcare Services",
    trainingInstitution: "SMC",
    trainingDuration: "12 months",
    graduationYear: 2023,
    employmentStatus: "Employed",
    sector: "Healthcare",
    skills: ["Patient Care", "Medical Records", "Health Education"],
    certifications: ["Healthcare Services Diploma", "First Aid Certification"],
    dateRegistered: "2023-01-08",
    contact: "mariama.sanneh@email.com",
  },
  {
    id: "NYSS_G009",
    name: "Ousman Jobe",
    age: 23,
    gender: "Male",
    region: "WCR",
    trainingProgram: "Green Energy & Sustainability",
    trainingInstitution: "GTTI",
    trainingDuration: "6 months",
    graduationYear: 2024,
    employmentStatus: "Employed",
    sector: "Renewable Energy",
    skills: ["Solar Installation", "Energy Auditing", "Environmental Management"],
    certifications: ["Green Energy Certificate"],
    dateRegistered: "2024-01-15",
    contact: "ousman.jobe@email.com",
  },
  {
    id: "NYSS_G010",
    name: "Binta Jallow",
    age: 22,
    gender: "Female",
    region: "GBA",
    trainingProgram: "Fashion & Textile Design",
    trainingInstitution: "NEDI",
    trainingDuration: "6 months",
    graduationYear: 2024,
    employmentStatus: "Self-Employed",
    sector: "Creative Industries",
    skills: ["Fashion Design", "Tailoring", "Pattern Making"],
    certifications: ["Fashion Design Diploma"],
    dateRegistered: "2024-02-10",
    contact: "binta.jallow@email.com",
  },
]

// NYSS Statistics
export const nyssStats = {
  totalPrograms: nyssPrograms.length,
  totalGraduates: nyssPrograms.reduce((sum, prog) => sum + prog.totalGraduates, 0),
  totalMale: nyssPrograms.reduce((sum, prog) => sum + prog.maleGraduates, 0),
  totalFemale: nyssPrograms.reduce((sum, prog) => sum + prog.femaleGraduates, 0),
  averageEmploymentRate:
    nyssPrograms.filter((p) => p.employmentRate > 0).reduce((sum, prog) => sum + prog.employmentRate, 0) /
    nyssPrograms.filter((p) => p.employmentRate > 0).length,
}

// Export aliases
export const nyssData = nyssGraduates
export const nyssGraduatesData = nyssGraduates
export const nyssProgramsData = nyssPrograms
