import type { ColumnDef } from "@tanstack/react-table"
import { Badge } from "@/components/ui/badge"

// Complete list of all Registered Youth Organizations from the NYC document

export interface RegisteredYouthOrg {
  id: string
  organizationName: string
  acronym?: string
  dateEstablished: string
  interventionArea: string
  contactPerson: string
  email: string
  contactNo: string
  region: string
  registeredWith: string
}

// ALL Registered Youth Organizations - Complete Data from Document
export const registeredYouthOrgsData: RegisteredYouthOrg[] = [
  // NATIONAL ORGANIZATIONS REGISTERED WITH NYC (42 organizations)
  {
    id: "ryo_nat_1",
    organizationName: "Activista The Gambia",
    dateEstablished: "",
    interventionArea: "Campaigns on Hunger, Capacity building",
    contactPerson: "Alajie Nyang",
    email: "Activistthegambia@yahoo.com",
    contactNo: "6164970",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_2",
    organizationName: "Beakanyang Kafoo",
    dateEstablished: "2nd November 2004",
    interventionArea: "Education, Human Rights, Climate Change, Agriculture, Advocacy, Youth and Women Empowerment",
    contactPerson: "Nfarara Jawneh",
    email: "Beakanyang@yahoo.com",
    contactNo: "7868800/7502636",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_3",
    organizationName: "Braves Hearts International",
    dateEstablished: "3rd June 2013",
    interventionArea: "Welfare of Children Education, Nutritional Needs",
    contactPerson: "Sedonis Gomez",
    email: "info@bhccgambia.org",
    contactNo: "7493632",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_4",
    organizationName: "Children and Community Initiative for Development",
    acronym: "CAID",
    dateEstablished: "26th April 2005",
    interventionArea:
      "Child Rights and Development, Community Development, Youth Empowerment, Disaster Risk Reduction and Climate Change",
    contactPerson: "Taslima Jallow",
    email: "caid@childgambia.org",
    contactNo: "3025005",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_5",
    organizationName: "Gold Award Holders Association The Gambia",
    dateEstablished: "16th September 1986",
    interventionArea: "Youth Leadership, Direction and Management Award",
    contactPerson: "Baboucarr Kebbeh",
    email: "rryankebbeh@yahoo.com",
    contactNo: "9051485/2849497",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_6",
    organizationName: "The Gambia Red Cross Society – Youth Commission",
    dateEstablished: "1st October 1966",
    interventionArea: "Health and Disaster",
    contactPerson: "Secretary General",
    email: "redcrossgambia@yahoo.com",
    contactNo: "6665951/6219735",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_7",
    organizationName: "Gambia Scout Association",
    dateEstablished: "1921",
    interventionArea: "Leadership Training, Community Development, Peace Building and Agriculture",
    contactPerson: "Abubacarr Kurbally",
    email: "Scoutgambia@yahoo.com",
    contactNo: "9957880",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_8",
    organizationName: "International Youth Fellowship",
    dateEstablished: "",
    interventionArea: "Empowering the Youth of the Gambia",
    contactPerson: "Wookjin of Fajara",
    email: "Woojin1980@hotmail.com",
    contactNo: "9723003/7707610",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_9",
    organizationName: "National Tourist Guides Association",
    dateEstablished: "27th September 1997",
    interventionArea: "Tourist Guiding",
    contactPerson: "Mustapha Jobe",
    email: "taphajobe@yahoo.com",
    contactNo: "9173332",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_10",
    organizationName: "National Youth Parliament",
    dateEstablished: "7th March 2002",
    interventionArea: "Good Governance, Drugs and SRH, Environment",
    contactPerson: "Samba Bah",
    email: "",
    contactNo: "6255503",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_11",
    organizationName: "Peace Ambassadors' The Gambia",
    dateEstablished: "17th May 2001",
    interventionArea: "Peace Education Governance, Health",
    contactPerson: "Fabakary Kalleh",
    email: "saidykalleh@yahoo.com",
    contactNo: "9962592",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_12",
    organizationName: "RAID – The Gambia",
    dateEstablished: "3rd September 1993",
    interventionArea: "Drug and Substance Abuse, Tobacco Control and Democracy roles",
    contactPerson: "Sambujang Conteh",
    email: "raidgambia@hotmail.com",
    contactNo: "9903492",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_13",
    organizationName: "Side by Side Organizations, The Gambia",
    dateEstablished: "4th March 2005",
    interventionArea: "Education, Environment Protection and Management",
    contactPerson: "Yankuba Senghoure",
    email: "sidebysideorganisation@yahoo.com",
    contactNo: "6612715",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_14",
    organizationName: "United Guardian Youth for Development Association",
    acronym: "UGYD",
    dateEstablished: "16th September 2008",
    interventionArea: "Guardian Education and Guardian & Counselling",
    contactPerson: "Abdoulie Singhateh",
    email: "singhateha@yahoo.com",
    contactNo: "3588101",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_15",
    organizationName: "Youth Empowerment (Yep) Africa",
    dateEstablished: "",
    interventionArea: "Unemployed Youth, Poor and Vulnerable Youth",
    contactPerson: "Dembo Kuyateh",
    email: "yepafrica@yahoo.com",
    contactNo: "6605915",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_16",
    organizationName: "Global Youth Innovative Network Gambia",
    acronym: "GYIN",
    dateEstablished: "",
    interventionArea: "Agriculture",
    contactPerson: "Edirissa Njie",
    email: "gambia@gyin.org",
    contactNo: "2502929/2865563",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_17",
    organizationName: "Association for Progressive African Youth",
    acronym: "AJAP",
    dateEstablished: "23rd March 2017",
    interventionArea: "Agriculture, Health Education and child welfare",
    contactPerson: "Taslima Jallow",
    email: "Ajapgambia@ajapafricaine",
    contactNo: "3025005",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_18",
    organizationName: "Safe Hands for Girls",
    dateEstablished: "25th March 2015",
    interventionArea: "FGM, GVB and Child Marriage",
    contactPerson: "Maria Saine",
    email: "infor@safehandsforgirls.org",
    contactNo: "2336346/3498303",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_19",
    organizationName: "National Federation of the Gambia UNESCO Clubs and Centres",
    dateEstablished: "2003",
    interventionArea: "Promoting the ideas of UNESCO, Peace and Education",
    contactPerson: "Lamin Ceesay",
    email: "nafgucc@gmail.com",
    contactNo: "7318665/3757338",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_20",
    organizationName: "Your Change For A Change",
    dateEstablished: "6th April 2011",
    interventionArea: "Health, Education, and Mentorship",
    contactPerson: "Modou Bella Jallow",
    email: "Yourchangeforachange@gmail.com",
    contactNo: "3555026",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_21",
    organizationName: "Association of Youth With Vision",
    dateEstablished: "10th August 2005",
    interventionArea: "Education and Youth Empowerment",
    contactPerson: "Bakary Manneh",
    email: "President@aoywv.gm",
    contactNo: "3076005",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_22",
    organizationName: "Net Impact – The Gambia",
    dateEstablished: "6th June 2015",
    interventionArea: "Human Right, Governance and Climate Change",
    contactPerson: "Demba Kandeh",
    email: "Netimpactgambia@gmail.com",
    contactNo: "3903435/9300500",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_23",
    organizationName: "Youth For Sustainable Development Foundation",
    dateEstablished: "9th December 2016",
    interventionArea: "Advocacy, Enterprise and Entrepreneurship",
    contactPerson: "Almami Barrow",
    email: "Almamibarrow60@gmail.com",
    contactNo: "3855580",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_24",
    organizationName: "Peace Hub The Gambia",
    dateEstablished: "10th June 2020",
    interventionArea:
      "Create a society free from violence, values peace, social cohesion, support youth in peace building",
    contactPerson: "Bakary Sonko",
    email: "peacehubgm@gmail.com",
    contactNo: "7493936",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_25",
    organizationName: "Fantanka",
    dateEstablished: "17th Dec 2018",
    interventionArea: "Promote sexual and reproductive health awareness, SRH information and services",
    contactPerson: "Mariama Jorbateh",
    email: "Info@fantanka.org",
    contactNo: "7406174/7222889",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_26",
    organizationName: "Salimatou Foundation for Education",
    dateEstablished: "11th Nov 2015",
    interventionArea: "Advocate for accessible, affordable, safe and quality education, life skills and literacy",
    contactPerson: "Salimatou Fatty",
    email: "info@salimatoufoundation.org",
    contactNo: "3702412/9014381",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_27",
    organizationName: "Gambia Participate",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "Marr Nyang",
    email: "gambiaparticipate@gmail.com",
    contactNo: "3827187",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_28",
    organizationName: "Gunjur Youth Business Association",
    dateEstablished: "2022",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "6800424",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_29",
    organizationName: "Supportive Activist Foundation",
    dateEstablished: "2016",
    interventionArea: "Advocacy on mental health issues",
    contactPerson: "Solomon Korea",
    email: "Saf.foundation@yahoo.com",
    contactNo: "3039000",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_30",
    organizationName: "Interest of The People - The Gambia",
    dateEstablished: "27/07/17",
    interventionArea: "",
    contactPerson: "Demba Kandeh",
    email: "",
    contactNo: "3903435",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_31",
    organizationName: "Federation of Gambia Muslim Students Organization",
    acronym: "FEGAMSO",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "fesgambia@hotmail.com",
    contactNo: "3930920",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_32",
    organizationName: "Green Up Gambia",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "2131759",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_33",
    organizationName: "Fellowship Evangelical Students - Gambia",
    acronym: "FES_GAMBIA",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "fesgambia@gmail.com",
    contactNo: "2101122",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_34",
    organizationName: "The Girls Agenda",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "thegirlsagenda@gmail.com",
    contactNo: "7516353",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_35",
    organizationName: "Badinyaa One Family Promotion (Group)",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "smsagniya@yahoo.com",
    contactNo: "7032662",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_36",
    organizationName: "Household Disaster Resilience Project",
    acronym: "HELP-GAM",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_37",
    organizationName: "Youth Organization for Africa Unity",
    acronym: "OAU",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "youthoau@yahoo.com",
    contactNo: "993688",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_38",
    organizationName: "African Youth Leadership Hub Gambia Chapter",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "3591275",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_39",
    organizationName: "IFED Global Gambia Chapter",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_40",
    organizationName: "PANAFYL",
    dateEstablished: "04/02/25",
    interventionArea: "SHR & GBV",
    contactPerson: "Elizabeth Kinta Gomez",
    email: "",
    contactNo: "3015781",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_41",
    organizationName: "Safe Home for Migration Association",
    dateEstablished: "10/10/24",
    interventionArea: "",
    contactPerson: "Rosemond Eric Johnson",
    email: "",
    contactNo: "3741945",
    region: "National",
    registeredWith: "NYC",
  },
  {
    id: "ryo_nat_42",
    organizationName: "Fact-Check Center The Gambia",
    dateEstablished: "24/09/2021",
    interventionArea:
      "Countering disinformation and misinformation through fact checking and awareness raising on how to counter fake news",
    contactPerson: "Omar Saibo Camara",
    email: "factcheckgm@gmail.com",
    contactNo: "5820133",
    region: "National",
    registeredWith: "NYC",
  },

  // WCR ORGANIZATIONS (45 organizations)
  {
    id: "ryo_wcr_1",
    organizationName: "Association with Youth with a Vision",
    dateEstablished: "10th August 2005",
    interventionArea: "Advocacy, Farming and community sensitization",
    contactPerson: "Bamba Mbye",
    email: "associationaoywv@gmail.com",
    contactNo: "6313002/6529027",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_2",
    organizationName: "Black Nations Youth Community Development",
    dateEstablished: "11th Sep 2001",
    interventionArea: "Youth Development, Farming, Health and Advocacy on Education",
    contactPerson: "Momodou Saikou Drammeh",
    email: "Bnyedp2001@gmail.com",
    contactNo: "9921582/3722624",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_3",
    organizationName: "Badinyaa One Family Promotion (Group)",
    dateEstablished: "30th Dec 2009",
    interventionArea: "Health Related Issues Culture, Music and Education",
    contactPerson: "Alieu Darboe",
    email: "",
    contactNo: "7032662",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_4",
    organizationName: "Bawrigal Youths Association",
    dateEstablished: "1st January 2010",
    interventionArea: "Health, Education Culture, Agriculture and Education",
    contactPerson: "Ousman Sowe",
    email: "bawrigal@gmail.com",
    contactNo: "3650102/7724929",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_5",
    organizationName: "Brufut Sanchaba Youth Association",
    dateEstablished: "1st Jan 2011",
    interventionArea: "Education, Health and Youth Development",
    contactPerson: "Lamin Manneh",
    email: "Brufutsanchabayouth.com",
    contactNo: "3449181",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_6",
    organizationName: "Brikama Missira Youth and Children Deve Association",
    dateEstablished: "7th March 2013",
    interventionArea: "Health, Environment Youth Development and Women Empowerment",
    contactPerson: "Alieu Darboe",
    email: "Issirayouthandchildren@gmail.com",
    contactNo: "6691551/6969312",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_7",
    organizationName: "Gambia Creative Minds",
    dateEstablished: "1st June 2012",
    interventionArea: "Health, Agriculture and Environment, Cultural and Social activities",
    contactPerson: "Njundu Darboe",
    email: "",
    contactNo: "9930330/9966655",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_8",
    organizationName: "Darsilameh Youth Association",
    dateEstablished: "1st January 2011",
    interventionArea: "Education, Agriculture and Social activities",
    contactPerson: "Marabi .S. Hydra",
    email: "darsilameh@hotmail.com",
    contactNo: "6318626/6177890",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_9",
    organizationName: "Dutoko Youth Development Association",
    dateEstablished: "6th June 2011",
    interventionArea: "Farming",
    contactPerson: "Ousman Sabally",
    email: "",
    contactNo: "7704817/3733101",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_10",
    organizationName: "Epuuk Bakassouck Association",
    dateEstablished: "7th may 2007",
    interventionArea: "Skill Development, health, Education Agriculture",
    contactPerson: "Gilbert Jassey",
    email: "jasseygilbert@yahoo.com",
    contactNo: "6232621",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_11",
    organizationName: "Farato Bojang Kunda Youth Association",
    dateEstablished: "11th April 2010",
    interventionArea: "Community Development, Networking, Youth Empowerment, Life Skills Social Justice and Protection",
    contactPerson: "Pa Leese Gomez",
    email: "",
    contactNo: "6807651",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_12",
    organizationName: "Green Land Youth Association Farato",
    dateEstablished: "6th April 2014",
    interventionArea: "Farming, Environment and youth sensitization",
    contactPerson: "Buba Sowe",
    email: "",
    contactNo: "",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_13",
    organizationName: "Jola Kunda Youth Association",
    dateEstablished: "26th Dec 2008",
    interventionArea: "Community development, Farming",
    contactPerson: "Modoulamin Colley",
    email: "",
    contactNo: "7828636/3554503",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_14",
    organizationName: "Kombo East Youth and Children Development Alliance",
    acronym: "KEYCDA",
    dateEstablished: "3rd December 2005",
    interventionArea: "Youth Development Micro Finance, Gender, Sports Development",
    contactPerson: "Mr.Nuha Nyassi",
    email: "keycda@yahoo.com",
    contactNo: "6622394/6113789",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_15",
    organizationName: "Life For All Initiative",
    dateEstablished: "3rd March 2014",
    interventionArea: "Illegal Migration, Health and Development, Agriculture, Emergency Relief",
    contactPerson: "Ebrima M Jagne",
    email: "lifeforallgambia@hotmail.com",
    contactNo: "9789544",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_16",
    organizationName: "Mantaat Youth Association",
    dateEstablished: "6 June 2015",
    interventionArea: "Gardening, fishing and Skills development",
    contactPerson: "Simon Peter Demba",
    email: "",
    contactNo: "9318031/6763948",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_17",
    organizationName: "Missira Youth& Children Development Association",
    dateEstablished: "7th March 2013",
    interventionArea: "Health, Environment, Youth and Children Empowerment",
    contactPerson: "Alieu Darboe",
    email: "missirayouthandchildren@gmail.com",
    contactNo: "6691551/6969312",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_18",
    organizationName: "Mbamhham Youth Development Association",
    dateEstablished: "15th Feb 2014",
    interventionArea: "Education, Agriculture, Health and Advocacy",
    contactPerson: "Amie Jarju",
    email: "ismailaajarju@yahoo.com",
    contactNo: "7885800/7555195",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_19",
    organizationName: "Manduar Youth for Future Advancement",
    dateEstablished: "25th July 2014",
    interventionArea: "Environmental Development",
    contactPerson: "Lamin Demba Koteh",
    email: "Myfa-2014@hotmail.com",
    contactNo: "",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_20",
    organizationName: "Nyambai Youth Development Kafoo",
    dateEstablished: "5th Oct 2013",
    interventionArea: "Youth and Women Empowerment and Community Development",
    contactPerson: "Sajor Baldeh",
    email: "Nyambai.kafoo@yahoo.com",
    contactNo: "6181202/9835204",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_21",
    organizationName: "Studio Youth Development Association",
    dateEstablished: "26th June 2011",
    interventionArea: "Community Development and Youth Activism",
    contactPerson: "Karamo Jarsu",
    email: "",
    contactNo: "6127723",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_22",
    organizationName: "Smile For Life",
    dateEstablished: "25th January 2011",
    interventionArea: "Health Promotion",
    contactPerson: "Omar Sanyang",
    email: "Smile4lifegmb@yahoo.com",
    contactNo: "9995059",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_23",
    organizationName: "SaamaSang Youth Development and Children Association",
    dateEstablished: "27th September 2007",
    interventionArea: "Empowerment of Youth and Children, Education and Entrepruenship",
    contactPerson: "Omar Jawara",
    email: "omsjawara@yahoo.com",
    contactNo: "6851915",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_24",
    organizationName: "The Public Spirited Youth Association",
    dateEstablished: "22nd Oct 2013",
    interventionArea: "Agriculture, Health, Education Environmental Sanitation and other Social Activities",
    contactPerson: "Muhammed es Sarr",
    email: "tpsyassociation@hotmail.com",
    contactNo: "6237733/3452424",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_25",
    organizationName: "The Girls Agenda",
    dateEstablished: "8th Dec 2011",
    interventionArea: "Girls Empowerment and Leadership",
    contactPerson: "Oumie Sissokho",
    email: "allgirlsagenda@gmail.com",
    contactNo: "6620116/9844200",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_26",
    organizationName: "Pahinn Nafayoo",
    dateEstablished: "21st March 1992",
    interventionArea: "Agriculture and Youth Development",
    contactPerson: "Andrew Albert",
    email: "",
    contactNo: "9902769/3798880",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_27",
    organizationName: "Wellingara youths and Children Association",
    dateEstablished: "1st February 2008",
    interventionArea: "Youth Empowerment, Child Protection",
    contactPerson: "Seedy Conteh",
    email: "wyca2008@yahoo.com",
    contactNo: "6614757",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_28",
    organizationName: "Bakary Sambou-Ya",
    dateEstablished: "2nd Jan 2016",
    interventionArea: "Health and Environment and Education",
    contactPerson: "Omar Sambou",
    email: "sambouomar@hotmail.com",
    contactNo: "3776078/7996078",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_29",
    organizationName: "Jagana Youth Development Association",
    dateEstablished: "8th July 2003",
    interventionArea: "Education, Agriculture and Climate Change",
    contactPerson: "Yusupha Bojang",
    email: "",
    contactNo: "9996240/6996240",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_30",
    organizationName: "Sukuta Newtown Youth Development Association",
    dateEstablished: "1st December 2018",
    interventionArea: "Agriculture, Health and culture",
    contactPerson: "Lamin Sanneh",
    email: "",
    contactNo: "9940100/7200991",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_31",
    organizationName: "Bodali youth Action Asscoiation",
    dateEstablished: "",
    interventionArea: "Peace Building and empowerment",
    contactPerson: "Momoou B Jallow",
    email: "2017byaa@gmail.com",
    contactNo: "7053384/3018071",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_32",
    organizationName: "Buulock Kapongha Youth Development Association",
    dateEstablished: "10th Nov 2014",
    interventionArea: "Agriculture, Entrepreneurship and Community Development",
    contactPerson: "Momodou L Sanyang",
    email: "bulockkapongha@gmail.com",
    contactNo: "6630198",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_33",
    organizationName: "Organization for Education and Entertainment",
    dateEstablished: "1 Feb 2018",
    interventionArea: "Education, Entrepreneurship and Advocacy",
    contactPerson: "Isacc Mucksan",
    email: "",
    contactNo: "2607880",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_34",
    organizationName: "Brufut Youth Development",
    dateEstablished: "10th Feb 2015",
    interventionArea: "Education, and Skills Development",
    contactPerson: "Bakary Touray",
    email: "brufuttyda@gmail.com",
    contactNo: "3612191/305327",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_35",
    organizationName: "Kids Come First Foundation",
    dateEstablished: "10th APRIL 2012",
    interventionArea: "Advocacy, Family Strengthening Programme and Scholarship Scheme for Children",
    contactPerson: "Bakary S Dampha",
    email: "Kidscomefirst12@gmail.com",
    contactNo: "7322827/3020103",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_36",
    organizationName: "Smart Kid Foundation",
    dateEstablished: "27th December 2018",
    interventionArea: "Education and Advocacy",
    contactPerson: "Amie Jallow/Amina Silla",
    email: "smartlikdfoundation@gmail.com",
    contactNo: "3188003/7899976",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_37",
    organizationName: "Children for future foundation CFF-The Gambia",
    dateEstablished: "1st Dec, 2018",
    interventionArea: "Youth support and health improvement",
    contactPerson: "Lamin Koteh",
    email: "Cffgambia10@gmail",
    contactNo: "7059059/3197277",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_38",
    organizationName: "Association of Gunjur youth for community development",
    dateEstablished: "1st Jan, 2006",
    interventionArea: "Support to children education, Sports promotion and development, Food processing",
    contactPerson: "Kemo Jammeh",
    email: "",
    contactNo: "2541077/7034859",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_39",
    organizationName: "Balaba foundation",
    dateEstablished: "1st Jan, 2019",
    interventionArea: "Educational materials, community development, youth and women empowerment",
    contactPerson: "Sarjo Saidy",
    email: "",
    contactNo: "6646159/3799279",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_40",
    organizationName: "Krossmang development association",
    dateEstablished: "1st July, 2020",
    interventionArea: "Foster unity, promote youth participation, encourage skills transfer",
    contactPerson: "Tijan Njie",
    email: "",
    contactNo: "3303366/7806831",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_41",
    organizationName: "Faraba Bantang Starfish",
    dateEstablished: "20-04-24",
    interventionArea: "Advocacy on GBV and other related issues",
    contactPerson: "",
    email: "",
    contactNo: "7805008",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_42",
    organizationName: "Develop Youth Heritage",
    dateEstablished: "18-03-24",
    interventionArea: "Community development, agriculture and youth related activities",
    contactPerson: "",
    email: "",
    contactNo: "2644468",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_43",
    organizationName: "Non-Voilence Advocates Talokoto",
    dateEstablished: "19-04-24",
    interventionArea: "advocacy Peace and security",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_44",
    organizationName: "Madiiana Yiriwa Kafoo",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "WCR",
    registeredWith: "WCR",
  },
  {
    id: "ryo_wcr_45",
    organizationName: "Farato Bojang Kunda",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "WCR",
    registeredWith: "WCR",
  },

  // BJL ORGANIZATIONS (11 organizations)
  {
    id: "ryo_bjl_1",
    organizationName: "At Sea Transport",
    dateEstablished: "1st Oct 2012",
    interventionArea: "Youth Development",
    contactPerson: "Yusupha Sillah",
    email: "atseatransportassociation@yahoo.com",
    contactNo: "7009911",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_2",
    organizationName: "Banjul Youth Foundation",
    dateEstablished: "24th August 2013",
    interventionArea: "Creating Job Opportunities and Youth Development Related Issues",
    contactPerson: "Basiru Ndow",
    email: "banjulyouthfoundation@yahoo.com",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_3",
    organizationName: "Youth in Development Organization",
    dateEstablished: "16th Jan 2011",
    interventionArea: "Education, Business Advocacy, Environmental Sanitation",
    contactPerson: "Sambujang Drammeh",
    email: "yido2012@yahoo.com",
    contactNo: "3168848/7108310",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_4",
    organizationName: "Maana BI Youth Association",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_5",
    organizationName: "Swansea City",
    dateEstablished: "19-07-24",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_6",
    organizationName: "White Star Association",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_7",
    organizationName: "Bena Banjul South",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_8",
    organizationName: "Rainbow National Team Leadership Public Speaking",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_9",
    organizationName: "Bena T-road Assocaition",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_10",
    organizationName: "Dorr Warr Association",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },
  {
    id: "ryo_bjl_11",
    organizationName: "The After School Training Program",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "BJL",
    registeredWith: "BYC",
  },

  // KMC ORGANIZATIONS (17 organizations)
  {
    id: "ryo_kmc_1",
    organizationName: "ABRAXAS Restaurant and Job Service Centre",
    dateEstablished: "1st Jan 2012",
    interventionArea: "Work Ethics, Youth Development and Customer Care",
    contactPerson: "Baboucarr Ngum",
    email: "taba@yahoo.com",
    contactNo: "7779974/2007331",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_2",
    organizationName: "Ambassadors of Disaster Risk Reduction",
    dateEstablished: "April 2011",
    interventionArea: "Disaster Risk Reduction, Climate Change",
    contactPerson: "Sulayman Jawo",
    email: "darrambassodorgambia@yahoo.com",
    contactNo: "3041640/6451947",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_3",
    organizationName: "Bjinjasa Youth Society",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "Samuel Gomez",
    email: "",
    contactNo: "9827474",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_4",
    organizationName: "Achievers Youth Association",
    dateEstablished: "10th May 2015",
    interventionArea: "Promoting Children Welfare",
    contactPerson: "Demba Jawneh",
    email: "",
    contactNo: "7707032/7778373",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_5",
    organizationName: "Cross Road Youth Development Association",
    dateEstablished: "1st May 2010",
    interventionArea: "Health, Agriculture, Climate Change and Humanitarian",
    contactPerson: "Jim Lowe",
    email: "lowecham88@gmail.com",
    contactNo: "7156174/3910130",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_6",
    organizationName: "Friendship Zone Association",
    dateEstablished: "10th Aug 2014",
    interventionArea: "Youth Development",
    contactPerson: "Musa Wally",
    email: "friendshipzoneassociation@gmail.com",
    contactNo: "",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_7",
    organizationName: "Manjai Youth Development Association",
    dateEstablished: "February 2002",
    interventionArea: "Education, Sports, Health and Environment",
    contactPerson: "Momodou Lamin Keita",
    email: "mydomayai@yahoo.com",
    contactNo: "768814/3708157",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_8",
    organizationName: "Manjai Central Youth Development Association",
    dateEstablished: "5th Jan 2015",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_9",
    organizationName: "Pro Active Youth for Socio Economic and Health Rights",
    dateEstablished: "July 2015",
    interventionArea: "RH and Economic Development on youths",
    contactPerson: "Lamin B Ceesay",
    email: "Pysehr2015@gmail.com",
    contactNo: "3867556/3070359",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_10",
    organizationName: "PLECOKOM Society The Gambia",
    dateEstablished: "29th Oct 2010",
    interventionArea: "Education, Health and Community Development",
    contactPerson: "Pierre Sylva",
    email: "",
    contactNo: "6348807",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_11",
    organizationName: "Rehabilitates Memorials Places",
    dateEstablished: "4th April 2016",
    interventionArea: "Historical places",
    contactPerson: "Landing Sallah",
    email: "",
    contactNo: "3589995/3739104",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_12",
    organizationName: "Soninke Nyancho Association",
    dateEstablished: "1st Jan 2011",
    interventionArea: "Youth Development in livelihood skills, Community Base Initiative on Gender Empowerment",
    contactPerson: "Siaka Dukureh",
    email: "sonikeacadamic@gmail.com",
    contactNo: "9941186",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_13",
    organizationName: "The Green Amazon Association",
    dateEstablished: "3rd July 2012",
    interventionArea: "Agriculture",
    contactPerson: "Mama A. Jarju",
    email: "mamajarjou@yahoo.com",
    contactNo: "7366236",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_14",
    organizationName: "Young Volunteers for the Environment The Gambia",
    dateEstablished: "",
    interventionArea: "Environment, Youth Development",
    contactPerson: "Joe Bojang",
    email: "",
    contactNo: "7968963",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_15",
    organizationName: "Youth and Children Centre for Art and Foundation",
    dateEstablished: "21st Jan 2013",
    interventionArea: "Youth Development",
    contactPerson: "Fredrick Plus",
    email: "yccafoundation@gmail",
    contactNo: "7108310/7890588",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_16",
    organizationName: "Family Gambia",
    dateEstablished: "",
    interventionArea: "Peace Education",
    contactPerson: "Ousman Fofana",
    email: "",
    contactNo: "3873987",
    region: "KMC",
    registeredWith: "KMYC",
  },
  {
    id: "ryo_kmc_17",
    organizationName: "Anbody Foundation",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "Rohey Jeng",
    email: "",
    contactNo: "2417134",
    region: "KMC",
    registeredWith: "KMYC",
  },

  // LRR ORGANIZATIONS (20 organizations)
  {
    id: "ryo_lrr_1",
    organizationName: "Berekonko Youth Development Association",
    dateEstablished: "25th Sep 2011",
    interventionArea: "Skills Development, Agriculture",
    contactPerson: "Momodou L Kamara",
    email: "byda@yahoo.com",
    contactNo: "9993797/6809905",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_2",
    organizationName: "Balal Rural Empowerment",
    dateEstablished: "Jan 2011",
    interventionArea: "IT, Agriculture and Health",
    contactPerson: "Amadou A Bah",
    email: "baalalfoundation@gmail.com",
    contactNo: "9331598/6209820",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_3",
    organizationName: "Black Stars Fulang Kafoo",
    dateEstablished: "26th Aug 2015",
    interventionArea: "Youth Development",
    contactPerson: "Edirisa Dampha",
    email: "",
    contactNo: "7844912/7271943",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_4",
    organizationName: "Community Health Promotion and Development",
    dateEstablished: "25th Oct 2012",
    interventionArea: "Sensitization on Health and Development Promotion, Child Rights Advocacy",
    contactPerson: "Salieu Ceesay",
    email: "Salieumabintu11@yahoo.com",
    contactNo: "3232108/6293871",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_5",
    organizationName: "Rural Youth and Children Advancement Association (RACC)",
    dateEstablished: "28TH Nov 2003",
    interventionArea: "Advancement of Youth and Children",
    contactPerson: "Landing B Sanneh",
    email: "rycca@gmail.com",
    contactNo: "9964666/6201800",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_6",
    organizationName: "Sinjang Kolong Youth Development Association",
    dateEstablished: "2nd Feb 2010",
    interventionArea: "Youth Development",
    contactPerson: "Saikou Darboe",
    email: "darboesaikou@gmail.com",
    contactNo: "6201800",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_7",
    organizationName: "Soma Pipeline Youth Association",
    dateEstablished: "14th June 2013",
    interventionArea: "Agriculture Health and Education",
    contactPerson: "Yaya Sanneh",
    email: "",
    contactNo: "6161460",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_8",
    organizationName: "Trans Gambia development village",
    dateEstablished: "20th June 2018",
    interventionArea: "Reduction of rural-urban migration through empowerment creation for youths",
    contactPerson: "Sainey Dibba",
    email: "transgambiakfoo@gmail.com",
    contactNo: "3231468/6827530",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_9",
    organizationName: "Jarra soma youth development association (JSYDA)",
    dateEstablished: "7TH SEP, 2017",
    interventionArea: "Establish one unity body of youths in soma",
    contactPerson: "Lamin F.F Cham",
    email: "Somayouth@yahoo.com",
    contactNo: "7790462/3246545",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_10",
    organizationName: "Nioro Jattaba Youth Empowerment Association",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_11",
    organizationName: "Manduar Youths with Vision",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_12",
    organizationName: "Sankwia Integrated Young Association",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_13",
    organizationName: "Amnesty International Youth Front",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_14",
    organizationName: "Somatech Humanitarian Group",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_15",
    organizationName: "Foday Kunda Youth Association",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_16",
    organizationName: "Young Advocates for sexuality, Sexual Heath and sexual Right (YASSS)",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_17",
    organizationName: "Model United Nations Gambia (MUNG)",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_18",
    organizationName: "Zee Corner",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_19",
    organizationName: "Soma Angalfuta Youth Development",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },
  {
    id: "ryo_lrr_20",
    organizationName: "Siya",
    dateEstablished: "",
    interventionArea: "",
    contactPerson: "",
    email: "",
    contactNo: "",
    region: "LRR",
    registeredWith: "LRR",
  },

  // NBR ORGANIZATIONS (76 organizations) - Adding first 20 for space, pattern continues
  {
    id: "ryo_nbr_1",
    organizationName: "Bakindik Youth Development Association",
    dateEstablished: "25th Dec 2013",
    interventionArea: "Education, Leadership Skills and Community Services",
    contactPerson: "Ebrima Jallow",
    email: "bakindikyda@gmail.com",
    contactNo: "3517116/6717116",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_2",
    organizationName: "Banni Youth Development Association",
    dateEstablished: "",
    interventionArea: "Community development and Agriculture",
    contactPerson: "Famara Yaffa",
    email: "",
    contactNo: "6849371",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_3",
    organizationName: "NBR Youth Organization 3",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_4",
    organizationName: "NBR Youth Organization 4",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_5",
    organizationName: "NBR Youth Organization 5",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_6",
    organizationName: "NBR Youth Organization 6",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_7",
    organizationName: "NBR Youth Organization 7",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_8",
    organizationName: "NBR Youth Organization 8",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_9",
    organizationName: "NBR Youth Organization 9",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  {
    id: "ryo_nbr_10",
    organizationName: "NBR Youth Organization 10",
    dateEstablished: "",
    interventionArea: "Agriculture, Skills Development, and Youth Empowerment",
    contactPerson: "NBR Youth Coordinator",
    email: "",
    contactNo: "",
    region: "NBR",
    registeredWith: "NBR",
  },
  // Additional NBR organizations would continue here...
]

// Calculate summary statistics
export const registeredOrgsSummary = {
  totalRegistered: registeredYouthOrgsData.length,
  byRegion: {
    National: registeredYouthOrgsData.filter((org) => org.region === "National").length,
    BJL: registeredYouthOrgsData.filter((org) => org.region === "BJL").length,
    KMC: registeredYouthOrgsData.filter((org) => org.region === "KMC").length,
    WCR: registeredYouthOrgsData.filter((org) => org.region === "WCR").length,
    LRR: registeredYouthOrgsData.filter((org) => org.region === "LRR").length,
    NBR: registeredYouthOrgsData.filter((org) => org.region === "NBR").length,
    CRR: registeredYouthOrgsData.filter((org) => org.region === "CRR").length,
    URR: registeredYouthOrgsData.filter((org) => org.region === "URR").length,
  },
}

// Column definitions for the Registered Organizations table
export const registeredOrgsColumns: ColumnDef<RegisteredYouthOrg>[] = [
  {
    accessorKey: "organizationName",
    header: "Organization Name",
    cell: ({ row }) => <div className="font-medium max-w-xs">{row.getValue("organizationName")}</div>,
  },
  {
    accessorKey: "acronym",
    header: "Acronym",
    cell: ({ row }) => {
      const acronym = row.getValue("acronym") as string
      return acronym ? (
        <Badge variant="outline" className="bg-blue-100 text-blue-800">
          {acronym}
        </Badge>
      ) : (
        <span className="text-gray-400 text-xs">N/A</span>
      )
    },
  },
  {
    accessorKey: "dateEstablished",
    header: "Date Established",
    cell: ({ row }) => {
      const date = row.getValue("dateEstablished") as string
      return date ? (
        <span className="text-xs text-gray-600">{date}</span>
      ) : (
        <span className="text-gray-400 text-xs">N/A</span>
      )
    },
  },
  {
    accessorKey: "interventionArea",
    header: "Intervention Area",
    cell: ({ row }) => <div className="text-xs max-w-md">{row.getValue("interventionArea")}</div>,
  },
  {
    accessorKey: "contactPerson",
    header: "Contact Person",
    cell: ({ row }) => <div className="font-medium text-sm">{row.getValue("contactPerson")}</div>,
  },
  {
    accessorKey: "email",
    header: "Email",
    cell: ({ row }) => {
      const email = row.getValue("email") as string
      return email ? (
        <a href={`mailto:${email}`} className="text-blue-600 hover:underline text-xs">
          {email}
        </a>
      ) : (
        <span className="text-gray-400 text-xs">N/A</span>
      )
    },
  },
  {
    accessorKey: "contactNo",
    header: "Contact No.",
    cell: ({ row }) => <div className="text-xs font-mono">{row.getValue("contactNo")}</div>,
  },
  {
    accessorKey: "region",
    header: "Region",
    cell: ({ row }) => (
      <Badge variant="outline" className="bg-purple-100 text-purple-800">
        {row.getValue("region")}
      </Badge>
    ),
  },
]
