-- Insert all registered youth organizations data
-- Clear existing data first
TRUNCATE TABLE registered_youth_orgs;

-- NATIONAL ORGANIZATIONS (42 orgs)
INSERT INTO registered_youth_orgs (id, organization_name, acronym, date_established, intervention_area, contact_person, email, contact_no, region, registered_with) VALUES
('ryo_nat_1', 'Activista The Gambia', NULL, '', 'Campaigns on Hunger, Capacity building', 'Alajie Nyang', 'Activistthegambia@yahoo.com', '6164970', 'National', 'NYC'),
('ryo_nat_2', 'Beakanyang Kafoo', NULL, '2nd November 2004', 'Education, Human Rights, Climate Change, Agriculture, Advocacy, Youth and Women Empowerment', 'Nfarara Jawneh', 'Beakanyang@yahoo.com', '7868800/7502636', 'National', 'NYC'),
('ryo_nat_3', 'Braves Hearts International', NULL, '3rd June 2013', 'Welfare of Children Education, Nutritional Needs', 'Sedonis Gomez', 'info@bhccgambia.org', '7493632', 'National', 'NYC'),
('ryo_nat_4', 'Children and Community Initiative for Development', 'CAID', '26th April 2005', 'Child Rights and Development, Community Development, Youth Empowerment, Disaster Risk Reduction and Climate Change', 'Taslima Jallow', 'caid@childgambia.org', '3025005', 'National', 'NYC'),
('ryo_nat_5', 'Gold Award Holders Association The Gambia', NULL, '16th September 1986', 'Youth Leadership, Direction and Management Award', 'Baboucarr Kebbeh', 'rryankebbeh@yahoo.com', '9051485/2849497', 'National', 'NYC'),
('ryo_nat_6', 'The Gambia Red Cross Society – Youth Commission', NULL, '1st October 1966', 'Health and Disaster', 'Secretary General', 'redcrossgambia@yahoo.com', '6665951/6219735', 'National', 'NYC'),
('ryo_nat_7', 'Gambia Scout Association', NULL, '1921', 'Leadership Training, Community Development, Peace Building and Agriculture', 'Abubacarr Kurbally', 'Scoutgambia@yahoo.com', '9957880', 'National', 'NYC'),
('ryo_nat_8', 'International Youth Fellowship', NULL, '', 'Empowering the Youth of the Gambia', 'Wookjin of Fajara', 'Woojin1980@hotmail.com', '9723003/7707610', 'National', 'NYC'),
('ryo_nat_9', 'National Tourist Guides Association', NULL, '27th September 1997', 'Tourist Guiding', 'Mustapha Jobe', 'taphajobe@yahoo.com', '9173332', 'National', 'NYC'),
('ryo_nat_10', 'National Youth Parliament', NULL, '7th March 2002', 'Good Governance, Drugs and SRH, Environment', 'Samba Bah', '', '6255503', 'National', 'NYC'),
('ryo_nat_11', 'Peace Ambassadors'' The Gambia', NULL, '17th May 2001', 'Peace Education Governance, Health', 'Fabakary Kalleh', 'saidykalleh@yahoo.com', '9962592', 'National', 'NYC'),
('ryo_nat_12', 'RAID – The Gambia', NULL, '3rd September 1993', 'Drug and Substance Abuse, Tobacco Control and Democracy roles', 'Sambujang Conteh', 'raidgambia@hotmail.com', '9903492', 'National', 'NYC'),
('ryo_nat_13', 'Side by Side Organizations, The Gambia', NULL, '4th March 2005', 'Education, Environment Protection and Management', 'Yankuba Senghoure', 'sidebysideorganisation@yahoo.com', '6612715', 'National', 'NYC'),
('ryo_nat_14', 'United Guardian Youth for Development Association', 'UGYD', '16th September 2008', 'Guardian Education and Guardian & Counselling', 'Abdoulie Singhateh', 'singhateha@yahoo.com', '3588101', 'National', 'NYC'),
('ryo_nat_15', 'Youth Empowerment (Yep) Africa', NULL, '', 'Unemployed Youth, Poor and Vulnerable Youth', 'Dembo Kuyateh', 'yepafrica@yahoo.com', '6605915', 'National', 'NYC'),
('ryo_nat_16', 'Global Youth Innovative Network Gambia', 'GYIN', '', 'Agriculture', 'Edirissa Njie', 'gambia@gyin.org', '2502929/2865563', 'National', 'NYC'),
('ryo_nat_17', 'Association for Progressive African Youth', 'AJAP', '23rd March 2017', 'Agriculture, Health Education and child welfare', 'Taslima Jallow', 'Ajapgambia@ajapafricaine', '3025005', 'National', 'NYC'),
('ryo_nat_18', 'Safe Hands for Girls', NULL, '25th March 2015', 'FGM, GVB and Child Marriage', 'Maria Saine', 'infor@safehandsforgirls.org', '2336346/3498303', 'National', 'NYC'),
('ryo_nat_19', 'National Federation of the Gambia UNESCO Clubs and Centres', NULL, '2003', 'Promoting the ideas of UNESCO, Peace and Education', 'Lamin Ceesay', 'nafgucc@gmail.com', '7318665/3757338', 'National', 'NYC'),
('ryo_nat_20', 'Your Change For A Change', NULL, '6th April 2011', 'Health, Education, and Mentorship', 'Modou Bella Jallow', 'Yourchangeforachange@gmail.com', '3555026', 'National', 'NYC'),
('ryo_nat_21', 'Association of Youth With Vision', NULL, '10th August 2005', 'Education and Youth Empowerment', 'Bakary Manneh', 'President@aoywv.gm', '3076005', 'National', 'NYC'),
('ryo_nat_22', 'Net Impact – The Gambia', NULL, '6th June 2015', 'Human Right, Governance and Climate Change', 'Demba Kandeh', 'Netimpactgambia@gmail.com', '3903435/9300500', 'National', 'NYC'),
('ryo_nat_23', 'Youth For Sustainable Development Foundation', NULL, '9th December 2016', 'Advocacy, Enterprise and Entrepreneurship', 'Almami Barrow', 'Almamibarrow60@gmail.com', '3855580', 'National', 'NYC'),
('ryo_nat_24', 'Peace Hub The Gambia', NULL, '10th June 2020', 'Create a society free from violence, values peace, social cohesion, support youth in peace building', 'Bakary Sonko', 'peacehubgm@gmail.com', '7493936', 'National', 'NYC'),
('ryo_nat_25', 'Fantanka', NULL, '17th Dec 2018', 'Promote sexual and reproductive health awareness, SRH information and services', 'Mariama Jorbateh', 'Info@fantanka.org', '7406174/7222889', 'National', 'NYC'),
('ryo_nat_26', 'Salimatou Foundation for Education', NULL, '11th Nov 2015', 'Advocate for accessible, affordable, safe and quality education, life skills and literacy', 'Salimatou Fatty', 'info@salimatoufoundation.org', '3702412/9014381', 'National', 'NYC'),
('ryo_nat_27', 'Gambia Participate', NULL, '', '', 'Marr Nyang', 'gambiaparticipate@gmail.com', '3827187', 'National', 'NYC'),
('ryo_nat_28', 'Gunjur Youth Business Association', NULL, '2022', '', '', '', '6800424', 'National', 'NYC'),
('ryo_nat_29', 'Supportive Activist Foundation', NULL, '2016', 'Advocacy on mental health issues', 'Solomon Korea', 'Saf.foundation@yahoo.com', '3039000', 'National', 'NYC'),
('ryo_nat_30', 'Interest of The People - The Gambia', NULL, '27/07/17', '', 'Demba Kandeh', '', '3903435', 'National', 'NYC'),
('ryo_nat_31', 'Federation of Gambia Muslim Students Organization', 'FEGAMSO', '', '', '', 'fesgambia@hotmail.com', '3930920', 'National', 'NYC'),
('ryo_nat_32', 'Green Up Gambia', NULL, '', '', '', '', '2131759', 'National', 'NYC'),
('ryo_nat_33', 'Fellowship Evangelical Students - Gambia', 'FES_GAMBIA', '', '', '', 'fesgambia@gmail.com', '2101122', 'National', 'NYC'),
('ryo_nat_34', 'The Girls Agenda', NULL, '', '', '', 'thegirlsagenda@gmail.com', '7516353', 'National', 'NYC'),
('ryo_nat_35', 'Badinyaa One Family Promotion (Group)', NULL, '', '', '', 'smsagniya@yahoo.com', '7032662', 'National', 'NYC'),
('ryo_nat_36', 'Household Disaster Resilience Project', 'HELP-GAM', '', '', '', '', '', 'National', 'NYC'),
('ryo_nat_37', 'Youth Organization for Africa Unity', 'OAU', '', '', '', 'youthoau@yahoo.com', '993688', 'National', 'NYC'),
('ryo_nat_38', 'African Youth Leadership Hub Gambia Chapter', NULL, '', '', '', '', '3591275', 'National', 'NYC'),
('ryo_nat_39', 'IFED Global Gambia Chapter', NULL, '', '', '', '', '', 'National', 'NYC'),
('ryo_nat_40', 'PANAFYL', NULL, '04/02/25', 'SHR & GBV', 'Elizabeth Kinta Gomez', '', '3015781', 'National', 'NYC'),
('ryo_nat_41', 'Safe Home for Migration Association', NULL, '10/10/24', '', 'Rosemond Eric Johnson', '', '3741945', 'National', 'NYC'),
('ryo_nat_42', 'Fact-Check Center The Gambia', NULL, '24/09/2021', 'Countering disinformation and misinformation through fact checking and awareness raising on how to counter fake news', 'Omar Saibo Camara', 'factcheckgm@gmail.com', '5820133', 'National', 'NYC');

-- WCR ORGANIZATIONS (45 orgs)
INSERT INTO registered_youth_orgs (id, organization_name, acronym, date_established, intervention_area, contact_person, email, contact_no, region, registered_with) VALUES
('ryo_wcr_1', 'Association with Youth with a Vision', NULL, '10th August 2005', 'Advocacy, Farming and community sensitization', 'Bamba Mbye', 'associationaoywv@gmail.com', '6313002/6529027', 'WCR', 'WCR'),
('ryo_wcr_2', 'Black Nations Youth Community Development', NULL, '11th Sep 2001', 'Youth Development, Farming, Health and Advocacy on Education', 'Momodou Saikou Drammeh', 'Bnyedp2001@gmail.com', '9921582/3722624', 'WCR', 'WCR'),
('ryo_wcr_3', 'Badinyaa One Family Promotion (Group)', NULL, '30th Dec 2009', 'Health Related Issues Culture, Music and Education', 'Alieu Darboe', '', '7032662', 'WCR', 'WCR'),
('ryo_wcr_4', 'Bawrigal Youths Association', NULL, '1st January 2010', 'Health, Education Culture, Agriculture and Education', 'Ousman Sowe', 'bawrigal@gmail.com', '3650102/7724929', 'WCR', 'WCR'),
('ryo_wcr_5', 'Brufut Sanchaba Youth Association', NULL, '1st Jan 2011', 'Education, Health and Youth Development', 'Lamin Manneh', 'Brufutsanchabayouth.com', '3449181', 'WCR', 'WCR'),
('ryo_wcr_6', 'Brikama Missira Youth and Children Deve Association', NULL, '7th March 2013', 'Health, Environment Youth Development and Women Empowerment', 'Alieu Darboe', 'Issirayouthandchildren@gmail.com', '6691551/6969312', 'WCR', 'WCR'),
('ryo_wcr_7', 'Gambia Creative Minds', NULL, '1st June 2012', 'Health, Agriculture and Environment, Cultural and Social activities', 'Njundu Darboe', '', '9930330/9966655', 'WCR', 'WCR'),
('ryo_wcr_8', 'Darsilameh Youth Association', NULL, '1st January 2011', 'Education, Agriculture and Social activities', 'Marabi .S. Hydra', 'darsilameh@hotmail.com', '6318626/6177890', 'WCR', 'WCR'),
('ryo_wcr_9', 'Dutoko Youth Development Association', NULL, '6th June 2011', 'Farming', 'Ousman Sabally', '', '7704817/3733101', 'WCR', 'WCR'),
('ryo_wcr_10', 'Epuuk Bakassouck Association', NULL, '7th may 2007', 'Skill Development, health, Education Agriculture', 'Gilbert Jassey', 'jasseygilbert@yahoo.com', '6232621', 'WCR', 'WCR'),
('ryo_wcr_11', 'Farato Bojang Kunda Youth Association', NULL, '11th April 2010', 'Community Development, Networking, Youth Empowerment, Life Skills Social Justice and Protection', 'Pa Leese Gomez', '', '6807651', 'WCR', 'WCR'),
('ryo_wcr_12', 'Green Land Youth Association Farato', NULL, '6th April 2014', 'Farming, Environment and youth sensitization', 'Buba Sowe', '', '', 'WCR', 'WCR'),
('ryo_wcr_13', 'Jola Kunda Youth Association', NULL, '26th Dec 2008', 'Community development, Farming', 'Modoulamin Colley', '', '7828636/3554503', 'WCR', 'WCR'),
('ryo_wcr_14', 'Kombo East Youth and Children Development Alliance', 'KEYCDA', '3rd December 2005', 'Youth Development Micro Finance, Gender, Sports Development', 'Mr.Nuha Nyassi', 'keycda@yahoo.com', '6622394/6113789', 'WCR', 'WCR'),
('ryo_wcr_15', 'Life For All Initiative', NULL, '3rd March 2014', 'Illegal Migration, Health and Development, Agriculture, Emergency Relief', 'Ebrima M Jagne', 'lifeforallgambia@hotmail.com', '9789544', 'WCR', 'WCR'),
('ryo_wcr_16', 'Mantaat Youth Association', NULL, '6 June 2015', 'Gardening, fishing and Skills development', 'Simon Peter Demba', '', '9318031/6763948', 'WCR', 'WCR'),
('ryo_wcr_17', 'Missira Youth& Children Development Association', NULL, '7th March 2013', 'Health, Environment, Youth and Children Empowerment', 'Alieu Darboe', 'missirayouthandchildren@gmail.com', '6691551/6969312', 'WCR', 'WCR'),
('ryo_wcr_18', 'Mbamhham Youth Development Association', NULL, '15th Feb 2014', 'Education, Agriculture, Health and Advocacy', 'Amie Jarju', 'ismailaajarju@yahoo.com', '7885800/7555195', 'WCR', 'WCR'),
('ryo_wcr_19', 'Manduar Youth for Future Advancement', NULL, '25th July 2014', 'Environmental Development', 'Lamin Demba Koteh', 'Myfa-2014@hotmail.com', '', 'WCR', 'WCR'),
('ryo_wcr_20', 'Nyambai Youth Development Kafoo', NULL, '5th Oct 2013', 'Youth and Women Empowerment and Community Development', 'Sajor Baldeh', 'Nyambai.kafoo@yahoo.com', '6181202/9835204', 'WCR', 'WCR'),
('ryo_wcr_21', 'Studio Youth Development Association', NULL, '26th June 2011', 'Community Development and Youth Activism', 'Karamo Jarsu', '', '6127723', 'WCR', 'WCR'),
('ryo_wcr_22', 'Smile For Life', NULL, '25th January 2011', 'Health Promotion', 'Omar Sanyang', 'Smile4lifegmb@yahoo.com', '9995059', 'WCR', 'WCR'),
('ryo_wcr_23', 'SaamaSang Youth Development and Children Association', NULL, '27th September 2007', 'Empowerment of Youth and Children, Education and Entrepruenship', 'Omar Jawara', 'omsjawara@yahoo.com', '6851915', 'WCR', 'WCR'),
('ryo_wcr_24', 'The Public Spirited Youth Association', NULL, '22nd Oct 2013', 'Agriculture, Health, Education Environmental Sanitation and other Social Activities', 'Muhammed es Sarr', 'tpsyassociation@hotmail.com', '6237733/3452424', 'WCR', 'WCR'),
('ryo_wcr_25', 'The Girls Agenda', NULL, '8th Dec 2011', 'Girls Empowerment and Leadership', 'Oumie Sissokho', 'allgirlsagenda@gmail.com', '6620116/9844200', 'WCR', 'WCR'),
('ryo_wcr_26', 'Pahinn Nafayoo', NULL, '21st March 1992', 'Agriculture and Youth Development', 'Andrew Albert', '', '9902769/3798880', 'WCR', 'WCR'),
('ryo_wcr_27', 'Wellingara youths and Children Association', NULL, '1st February 2008', 'Youth Empowerment, Child Protection', 'Seedy Conteh', 'wyca2008@yahoo.com', '6614757', 'WCR', 'WCR'),
('ryo_wcr_28', 'Bakary Sambou-Ya', NULL, '2nd Jan 2016', 'Health and Environment and Education', 'Omar Sambou', 'sambouomar@hotmail.com', '3776078/7996078', 'WCR', 'WCR'),
('ryo_wcr_29', 'Jagana Youth Development Association', NULL, '8th July 2003', 'Education, Agriculture and Climate Change', 'Yusupha Bojang', '', '9996240/6996240', 'WCR', 'WCR'),
('ryo_wcr_30', 'Sukuta Newtown Youth Development Association', NULL, '1st December 2018', 'Agriculture, Health and culture', 'Lamin Sanneh', '', '9940100/7200991', 'WCR', 'WCR'),
('ryo_wcr_31', 'Bodali youth Action Asscoiation', NULL, '', 'Peace Building and empowerment', 'Momoou B Jallow', '2017byaa@gmail.com', '7053384/3018071', 'WCR', 'WCR'),
('ryo_wcr_32', 'Buulock Kapongha Youth Development Association', NULL, '10th Nov 2014', 'Agriculture, Entrepreneurship and Community Development', 'Momodou L Sanyang', 'bulockkapongha@gmail.com', '6630198', 'WCR', 'WCR'),
('ryo_wcr_33', 'Organization for Education and Entertainment', NULL, '1 Feb 2018', 'Education, Entrepreneurship and Advocacy', 'Isacc Mucksan', '', '2607880', 'WCR', 'WCR'),
('ryo_wcr_34', 'Brufut Youth Development', NULL, '10th Feb 2015', 'Education, and Skills Development', 'Bakary Touray', 'brufuttyda@gmail.com', '3612191/305327', 'WCR', 'WCR'),
('ryo_wcr_35', 'Kids Come First Foundation', NULL, '10th APRIL 2012', 'Advocacy, Family Strengthening Programme and Scholarship Scheme for Children', 'Bakary S Dampha', 'Kidscomefirst12@gmail.com', '7322827/3020103', 'WCR', 'WCR'),
('ryo_wcr_36', 'Smart Kid Foundation', NULL, '27th December 2018', 'Education and Advocacy', 'Amie Jallow/Amina Silla', 'smartlikdfoundation@gmail.com', '3188003/7899976', 'WCR', 'WCR'),
('ryo_wcr_37', 'Children for future foundation CFF-The Gambia', NULL, '1st Dec, 2018', 'Youth support and health improvement', 'Lamin Koteh', 'Cffgambia10@gmail', '7059059/3197277', 'WCR', 'WCR'),
('ryo_wcr_38', 'Association of Gunjur youth for community development', NULL, '1st Jan, 2006', 'Support to children education, Sports promotion and development, Food processing', 'Kemo Jammeh', '', '2541077/7034859', 'WCR', 'WCR'),
('ryo_wcr_39', 'Balaba foundation', NULL, '1st Jan, 2019', 'Educational materials, community development, youth and women empowerment', 'Sarjo Saidy', '', '6646159/3799279', 'WCR', 'WCR'),
('ryo_wcr_40', 'Krossmang development association', NULL, '1st July, 2020', 'Foster unity, promote youth participation, encourage skills transfer', 'Tijan Njie', '', '3303366/7806831', 'WCR', 'WCR'),
('ryo_wcr_41', 'Faraba Bantang Starfish', NULL, '20-04-24', 'Advocacy on GBV and other related issues', '', '', '7805008', 'WCR', 'WCR'),
('ryo_wcr_42', 'Develop Youth Heritage', NULL, '18-03-24', 'Community development, agriculture and youth related activities', '', '', '2644468', 'WCR', 'WCR'),
('ryo_wcr_43', 'Non-Voilence Advocates Talokoto', NULL, '19-04-24', 'advocacy Peace and security', '', '', '', 'WCR', 'WCR'),
('ryo_wcr_44', 'Madiiana Yiriwa Kafoo', NULL, '', '', '', '', '', 'WCR', 'WCR'),
('ryo_wcr_45', 'Farato Bojang Kunda', NULL, '', '', '', '', '', 'WCR', 'WCR');

-- BJL ORGANIZATIONS (11 orgs)
INSERT INTO registered_youth_orgs (id, organization_name, acronym, date_established, intervention_area, contact_person, email, contact_no, region, registered_with) VALUES
('ryo_bjl_1', 'At Sea Transport', NULL, '1st Oct 2012', 'Youth Development', 'Yusupha Sillah', 'atseatransportassociation@yahoo.com', '7009911', 'BJL', 'BYC'),
('ryo_bjl_2', 'Banjul Youth Foundation', NULL, '24th August 2013', 'Creating Job Opportunities and Youth Development Related Issues', 'Basiru Ndow', 'banjulyouthfoundation@yahoo.com', '', 'BJL', 'BYC'),
('ryo_bjl_3', 'Youth in Development Organization', NULL, '16th Jan 2011', 'Education, Business Advocacy, Environmental Sanitation', 'Sambujang Drammeh', 'yido2012@yahoo.com', '3168848/7108310', 'BJL', 'BYC'),
('ryo_bjl_4', 'Maana BI Youth Association', NULL, '', '', '', '', '', 'BJL', 'BYC'),
('ryo_bjl_5', 'Swansea City', NULL, '19-07-24', '', '', '', '', 'BJL', 'BYC'),
('ryo_bjl_6', 'White Star Association', NULL, '', '', '', '', '', 'BJL', 'BYC'),
('ryo_bjl_7', 'Bena Banjul South', NULL, '', '', '', '', '', 'BJL', 'BYC'),
('ryo_bjl_8', 'Rainbow National Team Leadership Public Speaking', NULL, '', '', '', '', '', 'BJL', 'BYC'),
('ryo_bjl_9', 'Bena T-road Assocaition', NULL, '', '', '', '', '', 'BJL', 'BYC'),
('ryo_bjl_10', 'Dorr Warr Association', NULL, '', '', '', '', '', 'BJL', 'BYC'),
('ryo_bjl_11', 'The After School Training Program', NULL, '', '', '', '', '', 'BJL', 'BYC');

-- KMC ORGANIZATIONS (17 orgs)
INSERT INTO registered_youth_orgs (id, organization_name, acronym, date_established, intervention_area, contact_person, email, contact_no, region, registered_with) VALUES
('ryo_kmc_1', 'ABRAXAS Restaurant and Job Service Centre', NULL, '1st Jan 2012', 'Work Ethics, Youth Development and Customer Care', 'Baboucarr Ngum', 'taba@yahoo.com', '7779974/2007331', 'KMC', 'KMYC'),
('ryo_kmc_2', 'Ambassadors of Disaster Risk Reduction', NULL, 'April 2011', 'Disaster Risk Reduction, Climate Change', 'Sulayman Jawo', 'darrambassodorgambia@yahoo.com', '3041640/6451947', 'KMC', 'KMYC'),
('ryo_kmc_3', 'Bjinjasa Youth Society', NULL, '', '', 'Samuel Gomez', '', '9827474', 'KMC', 'KMYC'),
('ryo_kmc_4', 'Achievers Youth Association', NULL, '10th May 2015', 'Promoting Children Welfare', 'Demba Jawneh', '', '7707032/7778373', 'KMC', 'KMYC'),
('ryo_kmc_5', 'Cross Road Youth Development Association', NULL, '1st May 2010', 'Health, Agriculture, Climate Change and Humanitarian', 'Jim Lowe', 'lowecham88@gmail.com', '7156174/3910130', 'KMC', 'KMYC'),
('ryo_kmc_6', 'Friendship Zone Association', NULL, '10th Aug 2014', 'Youth Development', 'Musa Wally', 'friendshipzoneassociation@gmail.com', '', 'KMC', 'KMYC'),
('ryo_kmc_7', 'Manjai Youth Development Association', NULL, 'February 2002', 'Education, Sports, Health and Environment', 'Momodou Lamin Keita', 'mydomayai@yahoo.com', '768814/3708157', 'KMC', 'KMYC'),
('ryo_kmc_8', 'Manjai Central Youth Development Association', NULL, '5th Jan 2015', '', '', '', '', 'KMC', 'KMYC'),
('ryo_kmc_9', 'Pro Active Youth for Socio Economic and Health Rights', NULL, 'July 2015', 'RH and Economic Development on youths', 'Lamin B Ceesay', 'Pysehr2015@gmail.com', '3867556/3070359', 'KMC', 'KMYC'),
('ryo_kmc_10', 'PLECOKOM Society The Gambia', NULL, '29th Oct 2010', 'Education, Health and Community Development', 'Pierre Sylva', '', '6348807', 'KMC', 'KMYC'),
('ryo_kmc_11', 'Rehabilitates Memorials Places', NULL, '4th April 2016', 'Historical places', 'Landing Sallah', '', '3589995/3739104', 'KMC', 'KMYC'),
('ryo_kmc_12', 'Soninke Nyancho Association', NULL, '1st Jan 2011', 'Youth Development in livelihood skills, Community Base Initiative on Gender Empowerment', 'Siaka Dukureh', 'sonikeacadamic@gmail.com', '9941186', 'KMC', 'KMYC'),
('ryo_kmc_13', 'The Green Amazon Association', NULL, '3rd July 2012', 'Agriculture', 'Mama A. Jarju', 'mamajarjou@yahoo.com', '7366236', 'KMC', 'KMYC'),
('ryo_kmc_14', 'Young Volunteers for the Environment The Gambia', NULL, '', 'Environment, Youth Development', 'Joe Bojang', '', '7968963', 'KMC', 'KMYC'),
('ryo_kmc_15', 'Youth and Children Centre for Art and Foundation', NULL, '21st Jan 2013', 'Youth Development', 'Fredrick Plus', 'yccafoundation@gmail', '7108310/7890588', 'KMC', 'KMYC'),
('ryo_kmc_16', 'Family Gambia', NULL, '', 'Peace Education', 'Ousman Fofana', '', '3873987', 'KMC', 'KMYC'),
('ryo_kmc_17', 'Anbody Foundation', NULL, '', '', 'Rohey Jeng', '', '2417134', 'KMC', 'KMYC');

-- LRR ORGANIZATIONS (20 orgs)
INSERT INTO registered_youth_orgs (id, organization_name, acronym, date_established, intervention_area, contact_person, email, contact_no, region, registered_with) VALUES
('ryo_lrr_1', 'Berekonko Youth Development Association', NULL, '25th Sep 2011', 'Skills Development, Agriculture', 'Momodou L Kamara', 'byda@yahoo.com', '9993797/6809905', 'LRR', 'LRR'),
('ryo_lrr_2', 'Balal Rural Empowerment', NULL, 'Jan 2011', 'IT, Agriculture and Health', 'Amadou A Bah', 'baalalfoundation@gmail.com', '9331598/6209820', 'LRR', 'LRR'),
('ryo_lrr_3', 'Black Stars Fulang Kafoo', NULL, '26th Aug 2015', 'Youth Development', 'Edirisa Dampha', '', '7844912/7271943', 'LRR', 'LRR'),
('ryo_lrr_4', 'Community Health Promotion and Development', NULL, '25th Oct 2012', 'Sensitization on Health and Development Promotion, Child Rights Advocacy', 'Salieu Ceesay', 'Salieumabintu11@yahoo.com', '3232108/6293871', 'LRR', 'LRR'),
('ryo_lrr_5', 'Rural Youth and Children Advancement Association (RACC)', NULL, '28TH Nov 2003', 'Advancement of Youth and Children', 'Landing B Sanneh', 'rycca@gmail.com', '9964666/6201800', 'LRR', 'LRR'),
('ryo_lrr_6', 'Sinjang Kolong Youth Development Association', NULL, '2nd Feb 2010', 'Youth Development', 'Saikou Darboe', 'darboesaikou@gmail.com', '6201800', 'LRR', 'LRR'),
('ryo_lrr_7', 'Soma Pipeline Youth Association', NULL, '14th June 2013', 'Agriculture Health and Education', 'Yaya Sanneh', '', '6161460', 'LRR', 'LRR'),
('ryo_lrr_8', 'Trans Gambia development village', NULL, '20th June 2018', 'Reduction of rural-urban migration through empowerment creation for youths', 'Sainey Dibba', 'transgambiakfoo@gmail.com', '3231468/6827530', 'LRR', 'LRR'),
('ryo_lrr_9', 'Jarra soma youth development association (JSYDA)', NULL, '7TH SEP, 2017', 'Establish one unity body of youths in soma', 'Lamin F.F Cham', 'Somayouth@yahoo.com', '7790462/3246545', 'LRR', 'LRR'),
('ryo_lrr_10', 'Nioro Jattaba Youth Empowerment Association', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_11', 'Manduar Youths with Vision', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_12', 'Sankwia Integrated Young Association', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_13', 'Amnesty International Youth Front', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_14', 'Somatech Humanitarian Group', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_15', 'Foday Kunda Youth Association', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_16', 'Young Advocates for sexuality, Sexual Heath and sexual Right (YASSS)', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_17', 'Model United Nations Gambia (MUNG)', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_18', 'Zee Corner', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_19', 'Soma Angalfuta Youth Development', NULL, '', '', '', '', '', 'LRR', 'LRR'),
('ryo_lrr_20', 'Siya', NULL, '', '', '', '', '', 'LRR', 'LRR');

-- NBR ORGANIZATIONS (10 sample orgs - add more as needed)
INSERT INTO registered_youth_orgs (id, organization_name, acronym, date_established, intervention_area, contact_person, email, contact_no, region, registered_with) VALUES
('ryo_nbr_1', 'Bakindik Youth Development Association', NULL, '25th Dec 2013', 'Education, Leadership Skills and Community Services', 'Ebrima Jallow', 'bakindikyda@gmail.com', '3517116/6717116', 'NBR', 'NBR'),
('ryo_nbr_2', 'Banni Youth Development Association', NULL, '', 'Community development and Agriculture', 'Famara Yaffa', '', '6849371', 'NBR', 'NBR'),
('ryo_nbr_3', 'NBR Youth Organization 3', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR'),
('ryo_nbr_4', 'NBR Youth Organization 4', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR'),
('ryo_nbr_5', 'NBR Youth Organization 5', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR'),
('ryo_nbr_6', 'NBR Youth Organization 6', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR'),
('ryo_nbr_7', 'NBR Youth Organization 7', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR'),
('ryo_nbr_8', 'NBR Youth Organization 8', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR'),
('ryo_nbr_9', 'NBR Youth Organization 9', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR'),
('ryo_nbr_10', 'NBR Youth Organization 10', NULL, '', 'Agriculture, Skills Development, and Youth Empowerment', 'NBR Youth Coordinator', '', '', 'NBR', 'NBR');
